export const PASSAGES = {
  english: {
    easy: [
      "The quick brown fox jumps over the lazy dog.",
      "She sells sea shells by the sea shore.",
      "All that glitters is not gold.",
      "A stitch in time saves nine.",
      "The cat sat on the mat near the door.",
      "Good things come to those who wait.",
      "Every day is a new chance to do good.",
      "Read a good book and learn something new today.",
      "The sun sets in the west and rises in the east.",
      "Hard work and patience lead to great success.",
      "Keep your hands on the home row keys and type.",
      "Flash cards help kids learn new words fast.",
      "Dogs and cats make great pets for the family.",
      "Ask a friend to help you if you feel stuck.",
      "Take a walk in the park on a sunny day.",
      "The big red barn is full of hay and horses.",
      "Jill and Jake had a great time at the lake.",
      "Add salt and stir the soup until it is done.",
    ],
    medium: [
      "JavaScript is a versatile programming language that powers modern web applications across the globe.",
      "React makes building user interfaces easier with its component-based architecture and virtual DOM.",
      "TypeScript adds static typing to JavaScript for better code quality and long-term maintainability.",
      "The history of computing stretches back to the early mechanical calculators of the 19th century.",
      "Reading books regularly improves your vocabulary, concentration, and critical thinking skills significantly.",
      "Climate change is one of the most pressing global challenges facing humanity in the 21st century.",
      "Effective communication is a key skill in both personal relationships and professional environments.",
      "The internet has transformed the way people access information and connect with each other worldwide.",
      "Artificial intelligence is reshaping industries from healthcare to finance and transportation sectors.",
      "A healthy diet and regular exercise are the foundations of long-term physical and mental well-being.",
      "Learning a new language opens doors to different cultures and ways of thinking about the world.",
      "The scientific method involves observation, hypothesis, experimentation, and drawing logical conclusions.",
      "Photography is the art of capturing moments in time through light, composition, and creative perspective.",
      "Project management requires balancing scope, time, and resources to deliver results on schedule.",
      "Cloud computing allows businesses to scale infrastructure dynamically without hardware investment.",
      "Critical thinking means analyzing facts to form a judgment rather than accepting claims at face value.",
    ],
    hard: [
      "Asynchronous programming allows developers to perform multiple operations concurrently without blocking the main execution thread, resulting in more responsive applications.",
      "The philosophy behind RESTful APIs emphasizes stateless communication, resource-oriented design, and uniform interfaces that improve interoperability across distributed systems.",
      "Machine learning algorithms process vast amounts of structured and unstructured data to identify patterns and make predictions based on historical training examples.",
      "Quantum computing leverages the principles of superposition and entanglement to solve computational problems that are intractable for classical computers.",
      "Cybersecurity professionals must stay ahead of evolving threat landscapes, including zero-day exploits, ransomware attacks, social engineering, and advanced persistent threats.",
      "The International Space Station orbits approximately 400 kilometers above Earth, traveling at 28,000 km/h and completing 16 orbits per day.",
      "Neuroplasticity refers to the brain's remarkable ability to reorganize itself by forming new neural connections throughout an individual's lifetime.",
      "Object-oriented programming (OOP) encapsulates data and behavior within classes, promoting code reuse through inheritance, polymorphism, and abstraction.",
      "The Pythagorean theorem states: a² + b² = c², where c is the hypotenuse of a right-angled triangle; this fundamental relationship underpins much of Euclidean geometry.",
      "The Theory of General Relativity, published by Einstein in 1915, revolutionized physics by describing gravity as the curvature of spacetime caused by mass and energy.",
      "Blockchain technology ensures data integrity through cryptographic hashing, distributed consensus mechanisms, and an immutable append-only ledger structure.",
      "The discovery of DNA's double-helix structure by Watson and Crick in 1953 opened a new era in molecular biology, enabling modern genetics and biotechnology.",
      "Constitutional democracy depends on the separation of powers, checks and balances, and an independent judiciary to protect individual rights and prevent abuse of power.",
      "Photosynthesis converts sunlight, water (H₂O), and carbon dioxide (CO₂) into glucose and oxygen through a complex series of light-dependent and light-independent reactions.",
      "The global supply chain disruptions of 2020-2022 revealed the fragility of just-in-time manufacturing and the critical importance of building resilient supply networks.",
      "Epidemiology studies the distribution and determinants of health-related events in populations, informing public health policy and disease-prevention strategies.",
    ],
    emails: [
      "Dear Mr. Johnson, I hope this email finds you well. Please find attached the quarterly report for your review.",
      "I hope this message finds you in good health. I am writing to follow up on our meeting from last Tuesday.",
      "Thank you for your prompt response. I have reviewed the documents and everything looks good from my end.",
      "Please be advised that the deadline for project submission has been moved to the 15th of this month.",
      "Dear Team, I wanted to take a moment to congratulate everyone on the successful product launch last week.",
      "I am reaching out to schedule a brief call at your earliest convenience to discuss the upcoming proposal.",
      "As per our discussion yesterday, I am sending you the revised pricing details for your careful consideration.",
      "Kindly confirm receipt of this email and let me know if you require any additional information from our side.",
      "I wanted to update you on the status of the ongoing project. We are currently on track and within budget.",
      "Please find attached the invoice for services rendered during the month of March. Payment is due in 30 days.",
      "Thank you for giving me the opportunity to present our solution. I look forward to hearing your feedback.",
      "I regret to inform you that we will need to postpone the scheduled meeting due to an unforeseen conflict.",
      "It was a pleasure speaking with you today. I will send over the relevant documents by end of business.",
      "We appreciate your continued partnership and look forward to a successful collaboration in the coming quarter.",
    ],
    coding: [
      "const greet = (name) => `Hello, ${name}!`; console.log(greet('World')); // Hello, World!",
      "function fibonacci(n) { return n <= 1 ? n : fibonacci(n - 1) + fibonacci(n - 2); }",
      "const arr = [1, 2, 3, 4, 5]; const doubled = arr.map(x => x * 2); // [2, 4, 6, 8, 10]",
      "async function fetchData(url) { const res = await fetch(url); return res.json(); }",
      "class Animal { constructor(name) { this.name = name; } speak() { console.log(`${this.name} speaks.`); } }",
      "const { key, count } = { key: 'value', count: 42, active: true }; // destructuring",
      "for (let i = 0; i < arr.length; i++) { if (arr[i] % 2 === 0) console.log(arr[i]); }",
      "import React, { useState, useEffect } from 'react'; // React hooks for state and side effects",
      "SELECT * FROM users WHERE active = 1 AND created_at > '2024-01-01' ORDER BY name ASC;",
      "git commit -m 'feat: add user authentication with JWT tokens and refresh token logic'",
      "try { const data = JSON.parse(input); } catch (err) { console.error('Parse error:', err.message); }",
      "def binary_search(arr, target): low, high = 0, len(arr) - 1 # O(log n) search",
      "npm install --save-dev eslint prettier && npx eslint --init // setup linting and formatting",
      "const promise = new Promise((resolve, reject) => { setTimeout(() => resolve('done'), 1000); });",
    ],
    islamic: [
      "Alhamdulillah means 'All praise is due to Allah, the Lord of all the worlds.'",
      "The Prophet Muhammad (peace be upon him) said: 'The best among you are those who learn the Quran and teach it.'",
      "SubhanAllah wa bihamdihi, SubhanAllah il-Azeem — Glory be to Allah; Glory be to Allah the Magnificent.",
      "Bismillah ir-Rahman ir-Raheem means 'In the name of Allah, the Most Gracious, the Most Merciful.'",
      "The five pillars of Islam are: Shahada, Salah, Zakah, Sawm (fasting), and Hajj (pilgrimage).",
      "Tawakkul means placing complete trust in Allah while taking all necessary and responsible actions in one's life.",
      "The Prophet (PBUH) said: 'Seek knowledge from the cradle to the grave.' Learning is a lifelong obligation in Islam.",
      "Insha'Allah means 'If Allah wills it.' Muslims say this when speaking about future plans and aspirations.",
      "Sadaqah jariyah refers to continuous charity whose reward continues to flow even after the person has passed away.",
      "The Night of Power (Laylat al-Qadr) is better than a thousand months and falls in the last ten nights of Ramadan.",
      "Islam teaches that cleanliness is half of faith: 'At-Tuhur (purification) is half of iman (faith).' — Hadith.",
      "Zakat requires Muslims who meet the minimum wealth threshold to donate 2.5% of their savings to those in need.",
      "Dhikr, the remembrance of Allah through Allahu Akbar and Astaghfirullah, brings peace and tranquility to the heart.",
      "The Quran was revealed over 23 years to the Prophet Muhammad (PBUH) as a complete guidance for all of humanity.",
    ],
    poetry: [
      "Two roads diverged in a yellow wood, and I — I took the one less traveled by, and that has made all the difference. — Robert Frost",
      "Shall I compare thee to a summer's day? Thou art more lovely and more temperate. — Shakespeare, Sonnet 18",
      "Do not go gentle into that good night. Old age should burn and rave at close of day. — Dylan Thomas",
      "I wandered lonely as a cloud that floats on high o'er vales and hills. — William Wordsworth",
      "Hope is the thing with feathers that perches in the soul and sings the tune without the words. — Emily Dickinson",
      "How do I love thee? Let me count the ways. I love thee to the depth and breadth and height my soul can reach. — E. B. Browning",
      "Death, be not proud, though some have called thee mighty and dreadful, for thou art not so. — John Donne",
      "If you can keep your head when all about you are losing theirs and blaming it on you. — Rudyard Kipling",
      "Tyger Tyger, burning bright, in the forests of the night; what immortal hand or eye could frame thy fearful symmetry? — William Blake",
      "Season of mists and mellow fruitfulness, close bosom-friend of the maturing sun. — John Keats",
      "Because I could not stop for Death, he kindly stopped for me; the carriage held but just ourselves and Immortality. — Emily Dickinson",
      "The woods are lovely, dark and deep, but I have promises to keep, and miles to go before I sleep. — Robert Frost",
      "Tell me not in mournful numbers, life is but an empty dream! For the soul is dead that slumbers. — Henry Wadsworth Longfellow",
      "I have measured out my life with coffee spoons. — T. S. Eliot, The Love Song of J. Alfred Prufrock",
    ],
    freelance: [
      "Thank you for considering my proposal. I have 5 years of experience in full-stack web development with React and Node.js.",
      "I reviewed your project requirements carefully and I am confident I can deliver a high-quality solution within your timeline.",
      "As a top-rated freelancer with a 99% Job Success Score, I bring both technical expertise and professional communication.",
      "I would love to schedule a quick call to better understand your vision and discuss how we can work together effectively.",
      "My approach involves first understanding your requirements in detail, then creating a project plan before any coding begins.",
      "Please see my portfolio at the link below. I have built similar projects for clients in the US, UK, and Australia.",
      "I am available full-time for this project and can start immediately. My timezone is UTC+5 and I overlap with EST hours.",
      "To ensure transparency, I provide daily progress updates and share code through GitHub for your review at any stage.",
      "I specialize in responsive web design and ensure all deliverables are tested across Chrome, Firefox, and Safari.",
      "I understand the importance of deadlines and have a strong track record of delivering projects on time and within budget.",
      "My fixed price bid includes all revisions until you are 100% satisfied with the final product delivered to you.",
      "Dear client, I noticed you need a WordPress plugin. I have built over 30 custom plugins for e-commerce and SaaS clients.",
      "I am a UI/UX designer with expertise in Figma and Adobe XD. I focus on user-centered design that drives conversions.",
      "Let's connect to discuss your data analysis needs. I have experience with Python, Pandas, and building insightful dashboards.",
    ],
    numbers: [
      "In 2024, the top 3 companies earned $1.5 billion, up 47% from the 2019 total of $980 million across 12 countries.",
      "Order #4521: 30 units at $8.99 each = $269.70. Apply 15% discount on orders over $200. Delivery by 07/08/2024.",
      "The 100-meter sprint world record is 9.58 seconds, set on August 16, 2009 in Berlin by Usain Bolt.",
      "Flight BA207 departs at 06:45 from Terminal 3, Gate 22B. Duration: 7h 40m. Seat: 14A. Ref: XK9025.",
      "Score breakdown: Task 1 — 45/50, Task 2 — 38/50, Task 3 — 47/50. Total: 130/150 = 86.7% — Grade A.",
      "Call us at 0300-1234567 between 9am and 6pm, Monday to Friday. After-hours hotline: 0800-999-0011.",
      "Server uptime this month: 99.97%. Downtime: 13 minutes across 2 incidents on April 4 and April 19.",
      "Population of Karachi: ~16,000,000. Area: 3,527 km². Founded: 1729. Elevation: 8m above sea level.",
      "Chapter 4, pages 112–138: read 27 pages. Notes due by Friday 3pm. Quiz covers sections 4.1 through 4.8.",
      "Buy 2 at $12.50, get 1 free. Sale ends 31st Dec. Max 3 per customer. In-store only. Offer code: SAVE30.",
      "Train departs 08:17 from Platform 6. Journey: 2h 35m. Arrive 10:52. Return ticket: £42.00. Booking ref: TN7814.",
      "Mix 250ml of solution A with 750ml of solution B at 37°C for 45 minutes. pH should read between 6.8 and 7.2.",
    ],
    symbols: [
      "Email: user@domain.com | Subject: Re: Invoice #INV-2024-07 | Attach: report_final_v2.pdf (2.4MB)",
      "Code review: if (x > 0 && y != null) { return x * (y + 1); } // check: x > 0 & y defined",
      "Markdown: **bold**, _italic_, `code`, [link](https://example.com), > blockquote, - list item",
      "CLI: git commit -m 'fix: resolve #42 — null pointer in auth' && git push origin main --no-verify",
      "Regex: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/ matches valid email addresses.",
      "Formula: =SUMIF(A2:A100,\">=50\",B2:B100) — sums column B where column A >= 50. Range: $B$2:$B$100.",
      "CSS: .card { background: rgba(0,0,0,0.8); border: 1px solid #334155; padding: 1rem 1.5rem; }",
      "Bash: grep -rn 'TODO\\|FIXME' ./src --include='*.ts' | sort | uniq -c | sort -rn > issues.log",
      "URL params: https://api.example.com/v2/users?page=1&limit=50&sort=created_at&order=desc&filter=active",
      "JSON: { \"user\": { \"id\": 42, \"name\": \"Ali\", \"roles\": [\"admin\", \"editor\"], \"active\": true } }",
      "Math: f(x) = (x^2 + 3x - 4) / (x - 1); domain: x != 1; range: (-inf, +inf); roots at x = 1 & x = -4.",
      "SSH: ssh -i ~/.ssh/id_rsa user@192.168.1.100 -p 22 -L 8080:localhost:3000 -N &",
    ],
    study: [
      "The French Revolution of 1789 marked a turning point in European history, overthrowing the monarchy and establishing the principles of liberty and equality.",
      "Photosynthesis is the process by which plants convert sunlight into chemical energy stored in glucose, releasing oxygen as a byproduct.",
      "The Industrial Revolution began in Britain in the late 18th century and fundamentally transformed manufacturing, transportation, and urban life.",
      "Cognitive psychology examines mental processes such as attention, memory, perception, problem-solving, and language comprehension in human beings.",
      "Newton's three laws of motion describe the relationship between forces acting on a body and the resulting acceleration and motion of that body.",
      "The Great Wall of China, stretching over 21,000 kilometers, was built over many centuries to protect Chinese states from northern invasions.",
      "In economics, supply and demand determines the price equilibrium at which markets clear and scarce resources are allocated most efficiently.",
      "DNA, or deoxyribonucleic acid, carries the genetic instructions for the development, functioning, and reproduction of all known living organisms.",
      "Shakespeare wrote 37 plays and 154 sonnets, exploring themes of love, betrayal, ambition, jealousy, and the complexity of the human condition.",
      "Plate tectonics explains how Earth's lithosphere is divided into moving plates whose interactions cause earthquakes, mountain building, and volcanic eruptions.",
      "The Roman Empire at its height in 117 AD stretched from Scotland in the north to Mesopotamia in the east and North Africa in the south.",
      "Mitosis is the process by which a single cell divides into two genetically identical daughter cells, ensuring continuity in all living organisms.",
      "The study of philosophy encompasses metaphysics, epistemology, ethics, logic, and aesthetics — the fundamental branches of human inquiry and reason.",
      "Climate science uses data from ice cores, tree rings, and ocean sediments to reconstruct Earth's temperature history over millions of years.",
    ],
  },

  urdu: {
    easy: [
      "تیز رفتار اور درست ٹائپنگ ایک قیمتی مہارت ہے۔",
      "یہ ایپلیکیشن آپ کو ٹائپنگ کی رفتار بڑھانے میں مدد دے گی۔",
      "روزانہ مشق کرنے سے آپ بہتر ہو جائیں گے۔",
      "پانی پیئو اور صحت مند رہو۔",
      "آج کا دن بہت اچھا ہے۔",
      "میں اسکول جاتا ہوں اور پڑھتا ہوں۔",
      "سورج مشرق میں نکلتا ہے اور مغرب میں غروب ہوتا ہے۔",
      "گھر میں سب مل کر کھانا کھاتے ہیں۔",
      "کتاب پڑھنا ایک اچھی عادت ہے۔",
      "بچے باغ میں کھیل رہے ہیں۔",
      "ماں نے مجھے پیار کیا اور گلے لگایا۔",
      "دوست وہ ہوتا ہے جو مشکل میں کام آئے۔",
      "نماز مومن کی معراج ہے۔",
      "پھل کھانا صحت کے لیے فائدہ مند ہے۔",
      "رات کو جلدی سونا اور صبح جلدی اٹھنا اچھا ہے۔",
      "پاکستان ہمارا پیارا وطن ہے۔",
    ],
    medium: [
      "کمپیوٹر کی سائنس میں ٹائپنگ کی رفتار بہت اہم ہے۔",
      "اردو میں ٹائپنگ سیکھنا آجکل بہت آسان ہو گیا ہے۔",
      "اچھی ٹائپنگ کی مہارت کام کی دنیا میں بہت مفید ہے۔",
      "علم انسان کو جانوروں سے ممتاز کرتا ہے اور اسے ترقی کی راہ پر ڈالتا ہے۔",
      "انٹرنیٹ نے دنیا کو ایک چھوٹے سے گاؤں میں تبدیل کر دیا ہے۔",
      "محنت اور لگن سے کوئی بھی مقصد حاصل کیا جا سکتا ہے۔",
      "اردو ادب کی دنیا میں بہت سے عظیم شاعر اور ادیب ہوئے ہیں۔",
      "صحت مند غذا اور ورزش ایک صحت مند زندگی کی بنیاد ہیں۔",
      "آج کے دور میں ڈیجیٹل مہارتیں بہت ضروری ہو گئی ہیں۔",
      "قرآن پاک مسلمانوں کے لیے سب سے بڑی نعمت اور رہنمائی کا ذریعہ ہے۔",
      "پاکستانی ثقافت مختلف روایات اور رسوم و رواج کا خوبصورت مجموعہ ہے۔",
      "دریائے سندھ کی تہذیب دنیا کی قدیم ترین تہذیبوں میں سے ایک ہے۔",
      "جب انسان محنت کرتا ہے تو اللہ اس کی مدد فرماتا ہے۔",
      "سردیوں میں گرم چائے پینا بہت لطف دیتا ہے۔",
      "بچوں کی اچھی تربیت والدین کی سب سے بڑی ذمہ داری ہے۔",
      "موسیقی اور فن ہر معاشرے کی تہذیب کا ایک اہم حصہ ہیں۔",
    ],
    hard: [
      "جدید تکنالوجی کے دور میں ڈیجیٹل مہارتیں انتہائی ضروری ہو گئی ہیں۔",
      "پروگرامنگ اور سفٹ ویئر ڈیولپمنٹ میں ٹائپنگ کی رفتار کامیابی کی کلید ہے۔",
      "مختلف زبانوں میں ٹائپنگ کی مشق سے آپ کی لکھنے کی صلاحیت میں اضافہ ہوتا ہے۔",
      "اقتصادی ترقی کے لیے تعلیم، صنعت، اور جدید ٹیکنالوجی کا امتزاج ناگزیر ہے۔",
      "اسلامی تہذیب نے قرونِ وسطیٰ میں علم، فلسفہ، طب اور ریاضی میں انقلابی کردار ادا کیا۔",
      "مصنوعی ذہانت آج کے دور میں صنعت سے طب تک ہر شعبے کو بدل رہی ہے۔",
      "عالمی درجۂ حرارت میں اضافہ ماحولیاتی تبدیلیوں کا سبب بن رہا ہے جو سیارۂ زمین کے لیے خطرناک ہے۔",
      "پاکستان کے آئین کے مطابق ہر شہری کو آزادی اظہار اور بنیادی حقوق حاصل ہیں۔",
      "جینیاتی سائنس نے موروثی بیماریوں کی تشخیص اور علاج میں نئے امکانات کھول دیے ہیں۔",
      "اردو ادب میں غزل، نظم، افسانہ، اور ناول سبھی اصناف خاص اہمیت کی حامل ہیں۔",
      "سائبر سیکیورٹی کے بغیر ڈیجیٹل دنیا میں محفوظ رہنا ناممکن ہے۔",
      "تاریخ اسلام میں سلاطین دہلی سے لے کر مغل بادشاہوں تک علم و فن کی سرپرستی ہوتی رہی۔",
    ],
    islamic: [
      "بِسْمِ اللہِ الرَّحْمٰنِ الرَّحِیْمِ — اللہ کے نام سے شروع جو بڑا مہربان نہایت رحم والا ہے۔",
      "الحمد للہ رب العالمین — تمام تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا رب ہے۔",
      "سبحان اللہ وبحمدہ سبحان اللہ العظیم — اللہ پاک ہے اور اس کی حمد ہو، اللہ بہت بڑا ہے۔",
      "لا الہ الا اللہ محمد رسول اللہ — اللہ کے سوا کوئی معبود نہیں، محمد اللہ کے رسول ہیں۔",
      "بے شک اللہ کے ذکر ہی سے دلوں کو اطمینان ملتا ہے — ذکر اللہ سب سے بڑی عبادت ہے۔",
      "نبی کریم ﷺ نے فرمایا: علم حاصل کرنا ہر مسلمان مرد اور عورت پر فرض ہے۔",
      "رمضان المبارک اسلامی سال کا نواں مہینہ ہے جس میں قرآن پاک نازل ہوا۔",
      "درود ابراہیمی پڑھنا ہمارے نبی ﷺ سے محبت کا اظہار اور سنت کی پیروی ہے۔",
      "توبہ اور استغفار سے اللہ تعالیٰ گناہ معاف فرماتا ہے، اسی لیے کثرت سے استغفار کریں۔",
      "جنت ماؤں کے قدموں تلے ہے — نبی کریم ﷺ نے ماں کے ساتھ حسن سلوک کی تاکید کی۔",
      "صبر کرنے والوں کے ساتھ اللہ تعالیٰ ہوتا ہے — صبر ایمان کا نصف حصہ ہے۔",
      "زکوۃ ادا کرنا ہر صاحبِ نصاب مسلمان پر فرض ہے، یہ معاشرے میں برکت لاتی ہے۔",
      "ماہِ رمضان میں تراویح، تہجد اور اعتکاف اللہ سے قربت کے خاص ذریعے ہیں۔",
      "دعا مومن کا ہتھیار ہے — اللہ سے ہر وقت دعا مانگتے رہنا چاہیے۔",
    ],
    poetry: [
      "خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے — خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے — علامہ اقبال",
      "ہزاروں سال نرگس اپنی بے نوری پہ روتی ہے — بڑی مشکل سے ہوتا ہے چمن میں دیدہ ور پیدا — اقبال",
      "دل ڈھونڈتا ہے پھر وہی فرصت کے رات دن — بیٹھے رہیں تصورِ جاناں کیے ہوئے — مرزا غالب",
      "ہم کو ان سے وفا کی ہے امید — جو نہیں جانتے وفا کیا ہے — مرزا غالب",
      "مجھ سے پہلی سی محبت مری محبوب نہ مانگ — فیض احمد فیض",
      "آج بازار میں پا بجولاں چلو — چشمِ نم جانِ شوریدہ کافی نہیں — فیض احمد فیض",
      "ستاروں سے آگے جہاں اور بھی ہیں — ابھی عشق کے امتحاں اور بھی ہیں — علامہ اقبال",
      "تم مرے پاس ہوتے ہو گویا — جب کوئی دوسرا نہیں ہوتا — میر تقی میر",
      "پرندے شاخوں پر بیٹھے ہیں — خاموش ہے سارا آسمان — پروین شاکر",
      "یہ جذبے کا عالم ہے یا دل کی بات — محبت کے موسم میں کیا آئی رات — پروین شاکر",
      "جب تک زندہ ہوں دل میں آرزو ہے — اور جب مر جاؤں تو کیا — ناصر کاظمی",
      "نہیں تیری تقدیر میں وہ شب — جو میرے خوابوں نے دیکھی تھی — احمد فراز",
      "بن کے مٹی خاک میں مل جائیں گے ہم — اور یہ باغ و بہار رہ جائے گا — احمد فراز",
    ],
  },

  arabic: {
    easy: [
      "الكتابة السريعة مهارة قيمة جداً في العصر الحديث.",
      "هذا التطبيق سيساعدك على تحسين مهارات الكتابة لديك.",
      "الممارسة اليومية ستجعلك أفضل وأسرع في الكتابة.",
      "أحب القراءة كثيراً لأنها تزيد من معلوماتي.",
      "الماء ضروري للحياة ويجب شربه بكميات كافية.",
      "الأسرة هي أساس المجتمع وركيزته الأولى.",
      "العلم نور والجهل ظلام، فاطلب العلم دائماً.",
      "الصباح يبدأ بالإفطار وشرب كوب من الماء النظيف.",
      "أتمنى لك يوماً سعيداً مليئاً بالنجاح والتوفيق.",
      "القرآن الكريم هو كلام الله المنزل على نبيه محمد.",
      "الطفل يلعب في الحديقة مع أصدقائه كل يوم.",
      "أنا طالب في المدرسة وأحب تعلم العلوم الجديدة.",
      "الأم هي الجنة في حياة كل إنسان.",
      "الشمس تشرق من الشرق وتغرب في الغرب.",
      "يجب أن نحافظ على البيئة لأجيال القادمة.",
      "الصداقة الحقيقية تقوم على الإخلاص والثقة المتبادلة.",
    ],
    medium: [
      "في علوم الحاسوب، سرعة الكتابة مهمة جداً للمبرمجين.",
      "تعلم الكتابة بسرعة في اللغة العربية أصبح أسهل من ذي قبل.",
      "مهارات الكتابة الجيدة مفيدة جداً في عالم العمل الحديث.",
      "التكنولوجيا الحديثة غيرت طريقة تواصلنا وتعلمنا بشكل جذري.",
      "التعليم هو المفتاح الذي يفتح أبواب النجاح والتقدم في الحياة.",
      "اللغة العربية من أقدم اللغات وأغناها بالمفردات والتعابير الأدبية.",
      "الصحة الجيدة تتطلب الغذاء المتوازن والرياضة المنتظمة.",
      "يجب علينا الاهتمام بتعليم أطفالنا القيم الأخلاقية منذ الصغر.",
      "الطاقة المتجددة مثل الطاقة الشمسية ستحل محل الوقود الأحفوري.",
      "مصر ذات تاريخ عريق يمتد لآلاف السنين منذ عهد الفراعنة العظام.",
      "الذكاء الاصطناعي يُحدث ثورة في مجالات الطب والاقتصاد والتعليم.",
      "التوازن بين العمل والراحة ضروري للصحة النفسية والجسدية.",
      "القراءة المنتظمة تُحسن مستوى اللغة وتُنمي التفكير النقدي.",
      "الأمانة في العمل هي أساس النجاح المهني والاحترام من الآخرين.",
      "البيئة النظيفة تعكس مستوى الوعي والحضارة في المجتمع.",
      "ذاكرة الحاسوب المؤقتة تُستخدم لحفظ البيانات أثناء المعالجة.",
    ],
    hard: [
      "في العصر الرقمي الحالي، أصبحت المهارات الرقمية ضرورية للجميع.",
      "البرمجة وتطوير البرامج يتطلبان سرعة وكفاءة عالية في الكتابة.",
      "ممارسة الكتابة في لغات مختلفة تحسن من قدرتك على التعبير والتواصل.",
      "الذكاء الاصطناعي يُعيد تشكيل مستقبل العمالة البشرية وأسواق الاقتصاد العالمية.",
      "الأبحاث العلمية تُشير إلى أن التغير المناخي يُهدد النظم البيئية والتنوع الحيوي.",
      "المنهجية العلمية تعتمد على الملاحظة والفرضية والتجربة والاستنتاج المنطقي.",
      "الثورة الصناعية الرابعة تجمع بين الذكاء الاصطناعي وإنترنت الأشياء والبيانات الضخمة.",
      "تطوير الأنظمة الموزعة يتطلب فهماً عميقاً لبروتوكولات التواصل والتزامن.",
      "السياسة الاقتصادية الكلية تشمل السياسات المالية والنقدية ومعدلات التضخم والبطالة.",
      "الهندسة الوراثية تمكنت من تعديل الجينوم البشري لعلاج الأمراض الوراثية المستعصية.",
      "الفلسفة الإسلامية في القرون الوسطى أسهمت في نقل التراث اليوناني وإثرائه بالفكر الإسلامي.",
      "حماية الخصوصية الرقمية وأمن المعلومات باتا من أولويات الحكومات والمؤسسات الكبرى.",
    ],
    islamic: [
      "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
      "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ الرَّحْمَنِ الرَّحِيمِ مَالِكِ يَوْمِ الدِّينِ",
      "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
      "قُلْ هُوَ اللَّهُ أَحَدٌ اللَّهُ الصَّمَدُ لَمْ يَلِدْ وَلَمْ يُولَدْ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
      "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ",
      "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
      "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ",
      "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
      "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
      "اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي وَاهْدِنِي وَعَافِنِي وَارْزُقْنِي",
      "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ نِعْمَ الْمَوْلَى وَنِعْمَ النَّصِيرُ",
      "إِنَّ مَعَ الْعُسْرِ يُسْرًا — فَإِنَّ مَعَ الْعُسْرِ يُسْرًا",
      "وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ",
      "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي يَفْقَهُوا قَوْلِي",
      "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
      "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ أَشْهَدُ أَن لَّا إِلَهَ إِلَّا أَنتَ أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
      "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ — آية الكرسي",
    ],
  },

  persian: {
    easy: [
      "نوشتن سریع یک مهارت بسیار ارزشمند است.",
      "این برنامه به شما کمک خواهد کرد تا سرعت تایپ خود را بهبود بخشید.",
      "تمرین روزانه شما را در تایپ بهتر و سریعتر می کند.",
      "آب برای زندگی ضروری است و باید به اندازه کافی نوشید.",
      "خانواده پایه و اساس جامعه است.",
      "علم نور است و جهل تاریکی.",
      "هر روز صبح با شادی و انرژی آغاز کنید.",
      "کتاب خواندن یک عادت بسیار خوب است.",
      "بچه ها در باغ با دوستانشان بازی می کنند.",
      "ایران کشور زیبایی با تاریخ و فرهنگ غنی است.",
      "مادر محبوب ترین انسان در زندگی هر کسی است.",
      "آفتاب از شرق طلوع می کند و در غرب غروب می کند.",
      "دوست خوب در سختی ها کنار شماست.",
      "غذای سالم و ورزش منظم برای سلامتی ضروری است.",
      "شب ها زود بخوابید و صبح ها زود بیدار شوید.",
      "زبان فارسی یکی از زیباترین زبان های دنیاست.",
    ],
    medium: [
      "در علوم کامپیوتر، سرعت تایپ برای برنامه نویسان بسیار مهم است.",
      "یادگیری تایپ سریع در زبان فارسی امروزه بسیار ساده شده است.",
      "مهارات خوب در تایپ در دنیای کار امروزی بسیار مفید است.",
      "فناوری مدرن روش ارتباط و یادگیری ما را به طور اساسی تغییر داده است.",
      "دانش کلیدی است که درهای موفقیت را در زندگی باز می کند.",
      "زبان فارسی یکی از غنی ترین زبان های دنیا از نظر ادبیات و شعر است.",
      "تعادل بین کار و استراحت برای سلامت روحی و جسمی ضروری است.",
      "ایران تاریخی چندین هزار ساله دارد که سرشار از تمدن و فرهنگ است.",
      "هوش مصنوعی در حال تغییر اساسی بسیاری از صنایع در سراسر جهان است.",
      "مطالعه منظم سطح زبان شما را بهبود می بخشد و تفکر انتقادی را تقویت می کند.",
      "محیط زیست سالم مسئولیت مشترک همه ما برای نسل های آینده است.",
    ],
    hard: [
      "در عصر دیجیتال امروزی، مهارات دیجیتالی برای همه ضروری شده اند.",
      "برنامه نویسی و توسعه نرم افزار نیاز به سرعت و دقت بالایی دارد.",
      "تمرین تایپ در زبان های مختلف مهارت ارتباطی شما را بهبود می بخشد.",
      "هوش مصنوعی و یادگیری ماشین در حال بازتعریف مرزهای توانایی بشر هستند.",
      "سیاست های اقتصاد کلان شامل سیاست های مالی، پولی، و مدیریت تورم و بیکاری است.",
      "فلسفه اسلامی در قرون وسطی سهم بزرگی در انتقال و غنی سازی میراث یونانی داشت.",
      "علم ژنتیک توانسته است روش های درمان بسیاری از بیماری های ارثی را کشف کند.",
      "در دنیای شبکه های توزیع شده، امنیت اطلاعات و رمزنگاری اهمیت حیاتی دارند.",
      "انقلاب صنعتی چهارم، فناوری های دیجیتال، زیستی، و فیزیکی را با یکدیگر ادغام می کند.",
    ],
    poetry: [
      "بشنو این نی چون شکایت می کند — از جدایی ها حکایت می کند — مولانا جلال الدین رومی",
      "آتش عشق است کاندر نی فتاد — جوشش عشق است کاندر می فتاد — مولانا رومی",
      "الا یا ایها الساقی ادر کاسا و ناولها — که عشق آسان نمود اول ولی افتاد مشکل ها — حافظ شیرازی",
      "حافظا در کنج فقر و خلوت شب های تار — تا بود وردت دعا و درس قرآن غم مخور — حافظ",
      "بوی بهبود ز اوضاع جهان می شنوم — شادی آورد گل و باد صبا می شنوم — حافظ شیرازی",
      "بنی آدم اعضای یک پیکرند — که در آفرینش ز یک گوهرند — سعدی شیرازی",
      "چو عضوی به درد آورد روزگار — دگر عضوها را نماند قرار — سعدی شیرازی",
      "آدمی در عالم خاکی نمی آید به دست — عالمی دیگر بباید ساخت و از نو آدمی — حافظ",
      "هر که آمد عمارت نو ساخت رفت — وز نو آمدگان پایش انداخت رفت — عمر خیام نیشابوری",
      "خیام اگر ز باده مستی خوش باش — با ماه رخی اگر نشستی خوش باش — عمر خیام",
      "گر مرد رهی میان خون باید رفت — از پای فتاده سرنگون باید رفت — عطار نیشابوری",
    ],
  },
}
