export const PASSAGE_CONTEXT = {
  english: {
    islamic: [
      {
        title: 'The Opening Praise — Alhamdulillah',
        source: 'Surah Al-Fatiha, 1:2',
        context: 'This phrase opens every chapter of the Quran and is recited in every unit of prayer. It is an expression of gratitude acknowledging that all praise belongs to Allah alone.',
        tip: 'Say Alhamdulillah at least 33 times after each prayer as part of the Sunnah dhikr.',
      },
      {
        title: 'Hadith on Quranic Excellence',
        source: 'Sahih Bukhari, Book 61, Hadith 545',
        context: "This authentic hadith highlights the supreme virtue of engaging with the Quran — both learning and teaching it. The Prophet (PBUH) placed teachers of the Quran at the highest rank among believers.",
        tip: 'Even learning one verse and sharing it earns this virtue. Begin with Al-Fatiha and the short surahs.',
      },
      {
        title: 'The Two Magnificent Phrases',
        source: 'Sahih Bukhari, Book 80, Hadith 6682',
        context: 'The Prophet (PBUH) said these two phrases are light on the tongue, heavy on the Scale (Mizan), and beloved to the Most Merciful. They are among the most rewarding of all dhikr.',
        tip: 'Recite SubhanAllah wa bihamdihi 100 times each morning and evening for immense reward.',
      },
      {
        title: 'Bismillah — The Opening Invocation',
        source: 'Surah Al-Fatiha, 1:1; Surah An-Naml, 27:30',
        context: "Bismillah is recited before every lawful action to seek Allah's blessing. The Prophet (PBUH) said every matter of importance not begun with Bismillah is cut off from blessing.",
        tip: 'Say Bismillah before eating, drinking, beginning work, or entering your home.',
      },
      {
        title: 'The Five Pillars of Islam',
        source: 'Sahih Bukhari, Book 2, Hadith 7; Sahih Muslim',
        context: "The Prophet (PBUH) described Islam as built upon these five pillars. Together they form the spiritual, physical, financial, and communal foundation of a Muslim's life.",
        tip: 'Reflect on each pillar and how it strengthens your connection to Allah and your community.',
      },
      {
        title: 'Tawakkul — Trust in Allah',
        source: 'Sunan Ibn Majah, Hadith 2444',
        context: "The Prophet (PBUH) advised a man to tie his camel first, then put his trust in Allah. Tawakkul is not passivity — it means doing your best while trusting Allah for the outcome.",
        tip: "Before any important task, make your best effort, then say: 'Tawakkaltu 'alallah.'",
      },
      {
        title: 'Hadith on Seeking Knowledge',
        source: 'Sunan Ibn Majah, Hadith 224',
        context: "Islam emphasizes lifelong learning as a religious duty. The Quran's first revealed word was 'Iqra' (Read). Seeking beneficial knowledge is among the highest acts of worship in Islam.",
        tip: 'Dedicate at least 30 minutes daily to Islamic studies, even reading one page of a scholarly book.',
      },
      {
        title: "Insha'Allah — If Allah Wills",
        source: 'Surah Al-Kahf, 18:23-24',
        context: "The Quran commands believers never to say 'I will do this tomorrow' without adding Insha'Allah. It reflects the Islamic belief that all events are subject to Allah's will and permission.",
        tip: "Insha'Allah is not an excuse for procrastination — pair it with genuine intention and action.",
      },
      {
        title: 'Sadaqah Jariyah — Continuous Charity',
        source: 'Sahih Muslim, Book 13, Hadith 1631',
        context: 'The Prophet (PBUH) mentioned three deeds whose reward continues after death: a continuous charity, beneficial knowledge, and a righteous child who prays for the parent.',
        tip: 'Plant a tree, donate to build a masjid or school, or sponsor educational content as sadaqah jariyah.',
      },
      {
        title: 'Laylat al-Qadr — The Night of Power',
        source: 'Surah Al-Qadr, 97:1-5; Sahih Bukhari',
        context: "The Night of Qadr is when the Quran was first revealed. The Quran states it is better than 1,000 months (~83 years) of worship. It is sought in the odd nights of Ramadan's last ten days.",
        tip: "The Prophet (PBUH) advised reciting: 'Allahumma innaka afuwwun tuhibbul afwa fa'fu anni' on this night.",
      },
      {
        title: 'Purity is Half of Faith',
        source: 'Sahih Muslim, Book 2, Hadith 432',
        context: 'This hadith emphasizes both physical cleanliness (wudu, ghusl, taharah) and spiritual purity (purity of heart from sin). Wudu before prayer is both an act of worship and a practice of hygiene.',
        tip: 'Maintain wudu throughout the day when possible; angels accompany those in a state of purity.',
      },
      {
        title: 'Zakat — Obligatory Almsgiving',
        source: 'Surah Al-Baqarah, 2:43; Surah At-Tawbah, 9:60',
        context: 'Zakat purifies wealth and reduces inequality within the Muslim community. It is given to eight categories of recipients including the poor, the destitute, and travelers in need.',
        tip: 'Calculate your zakat annually on savings held for one lunar year above the nisab threshold.',
      },
      {
        title: "Dhikr — Remembrance of Allah",
        source: 'Surah Ar-Ra\'d, 13:28',
        context: "The Quran states: 'Verily in the remembrance of Allah do hearts find rest.' Dhikr keeps the heart connected to its Creator and shields it from heedlessness and spiritual hardness.",
        tip: 'Use a tasbih to count 33 SubhanAllah, 33 Alhamdulillah, 33 Allahu Akbar after each prayer.',
      },
      {
        title: 'The Revelation of the Quran',
        source: 'Surah Al-Baqarah, 2:185; Surah Al-Isra, 17:106',
        context: 'The Quran was revealed gradually over 23 years to address specific events and provide timeless guidance. It began with Iqra in the Cave of Hira and was completed before the Prophet\'s passing.',
        tip: 'Read the Quran daily with translation and tafsir to understand the context and guidance of each verse.',
      },
    ],

    coding: [
      {
        title: 'Arrow Function with Template Literal',
        concept: 'Arrow Functions & Template Literals',
        context: 'Arrow functions are a concise ES6 syntax for writing functions. Combined with template literals (backtick strings), they allow clean string interpolation. This greet function elegantly combines both features.',
        tip: "Use arrow functions for callbacks and short utilities. Use regular functions when you need 'this' binding.",
      },
      {
        title: 'Recursive Fibonacci Function',
        concept: 'Recursion',
        context: 'This implements the Fibonacci sequence using recursion. While elegant, the naive approach has O(2^n) complexity due to redundant calls. For large n, use memoization or an iterative approach instead.',
        tip: 'Use memoization (caching results) or a loop to optimize recursive functions for real-world performance.',
      },
      {
        title: 'Array map() Method',
        concept: 'Functional Array Methods',
        context: 'The map() method creates a new array by applying a transformation function to each element without mutating the original. This example doubles each number cleanly using an arrow function.',
        tip: 'Prefer map(), filter(), and reduce() over for loops for cleaner, more functional-style code.',
      },
      {
        title: 'Async/Await Data Fetching',
        concept: 'Asynchronous JavaScript',
        context: 'The async/await syntax allows writing asynchronous code that reads synchronously. The await keyword pauses execution until the Promise resolves, making API calls much easier to reason about.',
        tip: 'Always wrap async/await in try/catch blocks to handle network errors and failed requests gracefully.',
      },
      {
        title: 'ES6 Class with Constructor',
        concept: 'Object-Oriented Programming',
        context: 'ES6 classes provide a cleaner syntax for creating objects with shared behavior. The constructor method initializes properties, while class methods define behavior shared across all instances.',
        tip: 'Use classes when modeling real-world entities with shared behavior. For simple data, plain objects suffice.',
      },
      {
        title: 'Object Destructuring',
        concept: 'Destructuring Assignment',
        context: 'Destructuring allows extracting specific properties from objects into named variables in a single statement. It is especially useful with function parameters and when working with API response objects.',
        tip: "You can rename and set defaults: const { key: newName = 'default' } = obj;",
      },
      {
        title: 'For Loop with Conditional',
        concept: 'Iteration & Conditional Logic',
        context: 'This classic for loop iterates over an array and prints only even numbers using the modulo operator. It demonstrates the fundamental building block of iteration in JavaScript.',
        tip: 'For readability, consider: arr.filter(x => x % 2 === 0).forEach(console.log) as a modern alternative.',
      },
      {
        title: 'React Hooks Import',
        concept: 'React Hooks — useState & useEffect',
        context: 'useState manages component-level state that triggers re-renders when updated. useEffect handles side effects like data fetching and subscriptions, running after renders based on a dependency array.',
        tip: 'Keep hooks at the top level of your component. Never call hooks inside loops, conditions, or nested functions.',
      },
      {
        title: 'SQL SELECT Query with Filters',
        concept: 'SQL Querying',
        context: 'This SQL query retrieves all columns from users where active = 1 and created after Jan 2024, sorted by name. The WHERE clause filters rows and ORDER BY determines sort order.',
        tip: 'Avoid SELECT * in production. Specify only the columns you need to reduce data transfer and improve speed.',
      },
      {
        title: 'Conventional Git Commit',
        concept: 'Version Control & Commit Conventions',
        context: 'Conventional Commits specify a format: type(scope): description. Types include feat, fix, docs, refactor, and chore. This makes git history readable and enables automated changelog generation.',
        tip: 'Keep commit messages short but descriptive. One commit per logical change makes reversion easier.',
      },
      {
        title: 'Try/Catch Error Handling',
        concept: 'Error Handling',
        context: 'JSON.parse() throws a SyntaxError if the input is invalid JSON. The try/catch block catches this error gracefully, logging the message without crashing the application or losing context.',
        tip: 'Always validate or sanitize user input before parsing. Provide meaningful error messages for debugging.',
      },
      {
        title: 'Binary Search Algorithm',
        concept: 'Search Algorithms — O(log n) Complexity',
        context: 'Binary search works on sorted arrays by repeatedly halving the search space. With O(log n) time complexity, it is dramatically faster than linear search for large datasets.',
        tip: 'Binary search requires a sorted array. Use it when you need fast lookups in large, sorted collections.',
      },
      {
        title: 'ESLint and Prettier Setup',
        concept: 'Code Quality Tooling',
        context: 'ESLint statically analyzes JavaScript for errors and style issues. Prettier handles code formatting automatically. Using both together ensures consistent, clean code across teams and projects.',
        tip: 'Configure .eslintrc and .prettierrc in your project root and add lint scripts to package.json.',
      },
      {
        title: 'Creating a Promise',
        concept: 'Promises & Asynchronous Patterns',
        context: 'Promises represent the eventual completion or failure of async operations. This example creates a Promise that resolves after 1 second using setTimeout, simulating a real async task.',
        tip: 'Prefer async/await over raw Promise chains for readability, but understand Promises as they are the foundation.',
      },
    ],

    poetry: [
      {
        title: 'The Road Not Taken',
        poet: 'Robert Frost',
        era: 'Modern Era, 1916',
        context: "Published in 1916, this iconic poem reflects on life choices and individuality. Frost intended it as gentle mockery of indecision, but it became an anthem of independent thinking and self-determination.",
      },
      {
        title: 'Sonnet 18 — Shall I Compare Thee',
        poet: 'William Shakespeare',
        era: 'Elizabethan Era, c. 1609',
        context: "One of Shakespeare's most celebrated sonnets, it praises the beloved's beauty as surpassing summer itself. The sonnet promises immortality through verse — the poem outlasting even the summer day it describes.",
      },
      {
        title: 'Do Not Go Gentle Into That Good Night',
        poet: 'Dylan Thomas',
        era: 'Modern Era, 1951',
        context: "Written as his father lay dying, this villanelle urges passionate resistance against death. It is one of the most quoted elegies in the English language, structured around the repeated plea to 'rage against the dying of the light.'",
      },
      {
        title: 'I Wandered Lonely as a Cloud (Daffodils)',
        poet: 'William Wordsworth',
        era: 'Romantic Era, 1807',
        context: "Inspired by a walk with his sister Dorothy in the Lake District in 1802, this poem celebrates nature's power to lift the human spirit. The daffodils become a source of lasting inner joy recalled long after.",
      },
      {
        title: 'Hope is the Thing with Feathers',
        poet: 'Emily Dickinson',
        era: 'American Romanticism, c. 1861',
        context: 'Dickinson personifies hope as a bird that sings endlessly and never asks for anything in return. Written during the Civil War era, it celebrates the quiet, persistent resilience of the human spirit.',
      },
      {
        title: 'How Do I Love Thee? (Sonnet 43)',
        poet: 'Elizabeth Barrett Browning',
        era: 'Victorian Era, 1850',
        context: "From 'Sonnets from the Portuguese,' this famous love sonnet enumerates the depths of devotion to Robert Browning. It remains one of history's most celebrated declarations of romantic love.",
      },
      {
        title: 'Death Be Not Proud (Holy Sonnet X)',
        poet: 'John Donne',
        era: 'Metaphysical Poetry, c. 1609',
        context: "Donne personifies Death and boldly challenges its supposed might. As a clergyman, Donne argues that Death is a slave to fate and chance, and that believers will awake to eternal life — so Death itself shall die.",
      },
      {
        title: 'If —',
        poet: 'Rudyard Kipling',
        era: 'Victorian/Edwardian Era, 1910',
        context: "Written as fatherly advice, 'If' describes the qualities of an ideal person — stoic, humble, and resilient. It was inspired by the statesman Leander Starr Jameson and remains one of Britain's most beloved poems.",
      },
      {
        title: 'The Tyger',
        poet: 'William Blake',
        era: 'Romantic Era, 1794',
        context: "From Songs of Experience, this poem questions what divine force could create such a fearsome creature. It contrasts with 'The Lamb' from Songs of Innocence, exploring duality — creation, power, and the nature of God.",
      },
      {
        title: 'To Autumn',
        poet: 'John Keats',
        era: 'Romantic Era, 1820',
        context: "Keats wrote 'To Autumn' in September 1819 after a walk near Winchester. The poem personifies autumn as a season of rich abundance and gentle decline, and is considered one of the finest odes in English literature.",
      },
      {
        title: 'Because I Could Not Stop for Death',
        poet: 'Emily Dickinson',
        era: 'American Romanticism, c. 1863',
        context: "Death is personified as a courteous gentleman escorting the speaker through life's stages to eternity. Dickinson treats death as a natural, unhurried passage — not a feared end but a quiet transition to immortality.",
      },
      {
        title: 'Stopping by Woods on a Snowy Evening',
        poet: 'Robert Frost',
        era: 'Modern Era, 1923',
        context: "This serene poem captures a moment of temptation to linger in beautiful, dark woods. 'Miles to go before I sleep' is widely read as a metaphor for duty, responsibility, and the unfinished journey of life.",
      },
      {
        title: 'A Psalm of Life',
        poet: 'Henry Wadsworth Longfellow',
        era: 'American Romanticism, 1838',
        context: "A counter to pessimistic views of existence, this poem urges action and purpose. Longfellow challenges the idea that life is merely a dream, calling readers to live fully, leave a mark, and act in the present.",
      },
      {
        title: 'The Love Song of J. Alfred Prufrock',
        poet: 'T. S. Eliot',
        era: 'Modernism, 1915',
        context: "Eliot's dramatic monologue presents the anxieties of a timid, middle-aged man paralyzed by self-consciousness and indecision. 'Coffee spoons' symbolize the triviality and smallness of modern life measured in routine.",
      },
    ],

    emails: [
      {
        title: 'Formal Report Submission',
        tip: 'Always reference the attachment explicitly in the email body to confirm its inclusion for the recipient.',
        context: 'Used when sending official reports to managers or clients. A formal tone with a clear subject line helps the recipient prioritize and locate the document quickly.',
      },
      {
        title: 'Meeting Follow-Up',
        tip: 'Send follow-ups within 24 hours of the meeting while details are fresh for both parties.',
        context: 'Follow-up emails maintain momentum after meetings. They show professionalism and ensure no action items are forgotten or misunderstood.',
      },
      {
        title: 'Document Acknowledgment',
        tip: 'Confirm receipt and briefly share your assessment promptly to keep the workflow moving forward.',
        context: 'Acknowledging receipt of documents prevents miscommunication and reassures the sender that their materials were received and given attention.',
      },
      {
        title: 'Deadline Change Notice',
        tip: 'Give as much advance notice as possible when changing deadlines to allow recipients to adjust plans.',
        context: 'Communicating deadline changes professionally prevents misunderstandings and allows team members to re-prioritize their workload accordingly.',
      },
      {
        title: 'Team Congratulations',
        tip: 'Be specific about what the team achieved rather than using generic praise for maximum impact and motivation.',
        context: 'Recognizing team successes publicly boosts morale and motivates continued high performance. These emails foster a positive and appreciative work culture.',
      },
      {
        title: 'Call Scheduling Request',
        tip: 'Offer 2-3 time slots to make scheduling easier for the recipient and reduce unnecessary back-and-forth.',
        context: 'Requesting a call via email is professional and gives the recipient time to prepare. Always state the purpose briefly in the email.',
      },
      {
        title: 'Revised Pricing Communication',
        tip: 'Reference the original discussion to provide context and show you were attentive to the conversation.',
        context: 'Sending revised proposals after discussions shows responsiveness. Always clearly highlight what changed from the previous version to save the reader time.',
      },
      {
        title: 'Confirmation Request',
        tip: 'Keep confirmation emails short. One clear ask is more effective than a long, multi-topic message.',
        context: 'Requesting confirmation ensures important information reaches the right person and creates an opening for any follow-up questions or clarifications.',
      },
      {
        title: 'Project Status Update',
        tip: 'Use bullet points for key milestones and next steps to make status emails easy to scan quickly.',
        context: 'Regular project updates keep stakeholders informed and build trust. They also create a documented paper trail of progress and decisions.',
      },
      {
        title: 'Invoice Submission',
        tip: 'Include payment terms, due date, and accepted payment methods clearly in every invoice email.',
        context: 'Invoice emails should be professional and include all necessary details to ensure timely payment and avoid any confusion about terms.',
      },
      {
        title: 'Post-Presentation Follow-Up',
        tip: 'Follow up within 24 hours of a presentation to sustain the recipient\'s interest and momentum.',
        context: 'Following up after presentations demonstrates enthusiasm and initiative. It gives you the chance to address lingering questions and move to next steps.',
      },
      {
        title: 'Meeting Postponement Notice',
        tip: 'Always apologize briefly for the inconvenience and propose alternative dates immediately in the same email.',
        context: 'Postponement emails should be sent as early as possible. Offering new times right away shows respect for the other party\'s schedule and commitment.',
      },
      {
        title: 'Post-Call Action Follow-Up',
        tip: 'Summarize key discussion points and next steps clearly so both parties have a shared written reference.',
        context: 'A brief follow-up email after a call confirms what was discussed and prevents confusion about commitments, timelines, or responsibilities.',
      },
      {
        title: 'Partnership Appreciation',
        tip: 'Express genuine appreciation and reference specific shared successes to make the email feel personal and thoughtful.',
        context: 'Relationship maintenance emails strengthen long-term client partnerships. They show you value the relationship beyond individual transactions and deliverables.',
      },
    ],

    freelance: [
      {
        title: 'Proposal Introduction',
        tip: 'Lead with your most relevant experience and quantify your expertise (years, technologies) in the opening line.',
        context: 'The opening of a freelance proposal determines whether the client reads further. Be confident, concise, and immediately relevant to their specific project.',
      },
      {
        title: 'Requirement Review Statement',
        tip: 'Explicitly state that you reviewed the job post — it separates you from copy-paste bidders immediately.',
        context: 'Demonstrating that you understand the client\'s requirements builds trust instantly and shows you are serious and attentive, not just mass-bidding.',
      },
      {
        title: 'Social Proof Statement',
        tip: 'Always mention your Job Success Score or ratings early — clients filter by these metrics before reading proposals.',
        context: 'Social proof (ratings, scores, client reviews) is the strongest trust signal on freelancing platforms. Mentioning it early reduces client hesitation significantly.',
      },
      {
        title: 'Discovery Call Request',
        tip: 'Propose a short, low-commitment call (15-20 min) rather than a long meeting to reduce friction for new clients.',
        context: 'Discovery calls help both parties determine fit before committing to a contract. It shows you value quality collaboration over just winning a bid.',
      },
      {
        title: 'Project Approach Explanation',
        tip: 'Outline your workflow (planning → design → development → testing) to show a professional process.',
        context: 'Explaining your methodology reassures clients that you will not just start coding without a plan. It demonstrates experience and reduces their perceived risk.',
      },
      {
        title: 'Portfolio Reference',
        tip: 'Link to 2-3 most relevant past projects, not your entire portfolio. Relevance beats quantity every time.',
        context: 'Showing past work from relevant industries or technology stacks dramatically increases proposal conversion rates and client confidence.',
      },
      {
        title: 'Availability Statement',
        tip: 'Always mention timezone overlap with the client\'s location to address communication concerns proactively.',
        context: 'Clients hiring globally worry about communication delays. Proactively stating your availability and overlap hours addresses this concern directly and builds trust.',
      },
      {
        title: 'Transparency Commitment',
        tip: 'Offering a shared GitHub repo or daily Slack updates is a top reason clients choose one freelancer over another.',
        context: 'Daily progress updates and shared code repositories eliminate the anxiety of "is this person actually working?" that clients commonly feel when hiring remotely.',
      },
      {
        title: 'Quality Assurance Promise',
        tip: 'Specify which browsers/devices you test on — this detail shows thoroughness and prevents post-delivery disputes.',
        context: 'Clients often do not think about cross-browser compatibility until issues arise. Proactively mentioning QA testing builds confidence in your deliverables.',
      },
      {
        title: 'Delivery Track Record',
        tip: 'Back up deadline claims with specific metrics or a review quote: "Delivered 3 days early — Client Review."',
        context: 'Late deliveries are among the biggest freelancer complaints. Addressing this concern directly and proactively is a powerful differentiator in a competitive proposal.',
      },
      {
        title: 'Fixed Price + Revisions Offer',
        tip: 'Specify the number of revision rounds: "up to 3 revision rounds" to prevent scope creep clearly.',
        context: 'A fixed-price model with clearly defined revisions builds client trust and reduces negotiation friction about hourly billing and unexpected costs.',
      },
      {
        title: 'Niche Specialization Statement',
        tip: 'Quantify your niche experience (30+ plugins, 5 years in e-commerce) to differentiate from generalist bidders.',
        context: 'Clients posting specialized jobs (WordPress, Shopify, data science) strongly prefer freelancers who specialize in their exact stack and have proven results.',
      },
      {
        title: 'Design Specialization Pitch',
        tip: 'Mention specific design deliverables (wireframes, prototypes, dev handoff specs) to show your full workflow expertise.',
        context: 'UI/UX designers must communicate tool proficiency and demonstrate they understand that design serves users and conversion, not just aesthetics.',
      },
      {
        title: 'Data Analysis Pitch',
        tip: 'Offer a small sample analysis or dashboard mockup as a hook — this is extremely effective for data proposals.',
        context: 'Data analysis proposals benefit from specificity. Mentioning tools (Python, Pandas) and deliverables (dashboards, reports) signals technical competence immediately.',
      },
    ],

    study: [
      {
        title: 'The French Revolution',
        concept: 'Political Revolution & Enlightenment Ideals',
        context: 'The French Revolution of 1789 was fueled by Enlightenment ideas of liberty, equality, and fraternity. It abolished the feudal system, executed King Louis XVI, and paved the way for modern democratic republics.',
      },
      {
        title: 'Photosynthesis',
        concept: 'Plant Biology & Energy Conversion',
        context: 'Photosynthesis occurs in chloroplasts through two stages: the light reactions (producing ATP and NADPH) and the Calvin cycle (fixing CO₂ into glucose). It is the foundation of nearly all food chains on Earth.',
      },
      {
        title: 'The Industrial Revolution',
        concept: 'Economic & Technological Transformation',
        context: 'The Industrial Revolution introduced steam power, textile mills, and railways, transforming Britain from an agrarian society into an industrial powerhouse. It created modern capitalism and gave rise to the urban working class.',
      },
      {
        title: 'Cognitive Psychology',
        concept: 'Mental Processes & Information Processing',
        context: 'Cognitive psychology emerged in the 1950s as a reaction against behaviorism. It models the mind as an information-processing system and has broad applications in education, therapy, and artificial intelligence design.',
      },
      {
        title: "Newton's Laws of Motion",
        concept: 'Classical Mechanics',
        context: "Isaac Newton published his three laws in Principia Mathematica (1687). The first law is inertia, the second relates force and acceleration (F=ma), and the third states every action has an equal and opposite reaction.",
      },
      {
        title: 'The Great Wall of China',
        concept: 'Ancient Architecture & Military History',
        context: 'Construction began as early as the 7th century BC, with major building during the Qin and Ming dynasties. The wall employed millions of laborers over centuries as both a military barrier and a symbol of Chinese civilization.',
      },
      {
        title: 'Supply and Demand',
        concept: 'Microeconomics',
        context: 'In a free market, prices rise when demand exceeds supply and fall when supply exceeds demand. The intersection of supply and demand curves is the equilibrium — the market-clearing price at which goods are efficiently allocated.',
      },
      {
        title: 'DNA — Blueprint of Life',
        concept: 'Molecular Biology & Genetics',
        context: 'DNA is a double-helix molecule made of nucleotide base pairs (A-T and G-C). The sequence of these bases encodes genes, which are transcribed into RNA and translated into proteins that perform all biological functions.',
      },
      {
        title: 'William Shakespeare — Literary Legacy',
        concept: 'Renaissance Literature & Drama',
        context: "Shakespeare's works, written between 1590 and 1613, include tragedies (Hamlet, Macbeth), comedies (A Midsummer Night's Dream), and histories (Henry V). His influence on the English language remains unparalleled.",
      },
      {
        title: 'Plate Tectonics',
        concept: 'Geology & Earth Science',
        context: 'The theory of plate tectonics, developed in the 1960s, explains that Earth\'s outer shell is divided into about 15 major plates moving a few centimeters per year. Their boundaries are where most geological activity occurs.',
      },
      {
        title: 'The Roman Empire at its Peak',
        concept: 'Ancient History & Imperialism',
        context: 'Under Emperor Trajan (98–117 AD), Rome reached its greatest territorial extent. Roman infrastructure — roads, aqueducts, and legal codes — shaped European civilization for centuries and influenced modern governance and language.',
      },
      {
        title: 'Mitosis — Cell Division',
        concept: 'Cell Biology',
        context: 'Mitosis has four phases: prophase, metaphase, anaphase, and telophase. Chromosomes condense, align, separate, and move to daughter cells. It drives growth, tissue repair, and asexual reproduction in living organisms.',
      },
      {
        title: 'The Branches of Philosophy',
        concept: 'Philosophy & Critical Inquiry',
        context: "Metaphysics asks 'What exists?', Epistemology asks 'What can we know?', Ethics asks 'How should we act?', Logic studies valid reasoning, and Aesthetics examines beauty and art — together forming the bedrock of critical thought.",
      },
      {
        title: 'Climate Science & Paleoclimatology',
        concept: 'Climate Science',
        context: 'Ice cores contain trapped air bubbles revealing ancient atmospheric CO₂ levels. Tree rings show annual growth patterns tied to temperature. These proxies confirm that current warming is unprecedented in human history.',
      },
    ],
  },

  urdu: {
    islamic: [
      {
        title: 'بسم اللہ الرحمٰن الرحیم',
        source: 'سورۃ الفاتحہ ۱:۱',
        urduMeaning: 'اللہ کے نام سے شروع جو بڑا مہربان نہایت رحم والا ہے',
        englishMeaning: 'In the name of Allah, the Most Gracious, the Most Merciful',
      },
      {
        title: 'الحمد للہ رب العالمین',
        source: 'سورۃ الفاتحہ ۱:۲',
        urduMeaning: 'تمام تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا پروردگار ہے',
        englishMeaning: 'All praise is due to Allah, Lord of all the worlds',
      },
      {
        title: 'تسبیح — سبحان اللہ وبحمدہ',
        source: 'صحیح بخاری، کتاب الدعوات',
        urduMeaning: 'اللہ پاک ہے اپنی تعریف کے ساتھ؛ اللہ بہت عظیم ہے',
        englishMeaning: 'Glory be to Allah and His is the praise; Glory be to Allah the Magnificent',
      },
      {
        title: 'کلمہ طیبہ',
        source: 'صحیح بخاری و مسلم',
        urduMeaning: 'اللہ کے سوا کوئی معبود نہیں، محمد ﷺ اللہ کے رسول ہیں',
        englishMeaning: 'There is no god but Allah; Muhammad is the Messenger of Allah',
      },
      {
        title: 'ذکر اللہ — دلوں کا اطمینان',
        source: 'سورۃ الرعد ۱۳:۲۸',
        urduMeaning: 'بے شک اللہ کے ذکر ہی سے دلوں کو سکون ملتا ہے',
        englishMeaning: 'Verily, in the remembrance of Allah do hearts find rest',
      },
      {
        title: 'طلبِ علم کی فرضیت',
        source: 'سنن ابن ماجہ، حدیث ۲۲۴',
        urduMeaning: 'علم حاصل کرنا ہر مسلمان مرد اور عورت پر فرض ہے',
        englishMeaning: 'Seeking knowledge is an obligation upon every Muslim man and woman',
      },
      {
        title: 'ماہِ رمضان المبارک',
        source: 'سورۃ البقرہ ۲:۱۸۵',
        urduMeaning: 'رمضان وہ مہینہ ہے جس میں قرآن پاک نازل کیا گیا جو لوگوں کے لیے ہدایت ہے',
        englishMeaning: 'Ramadan is the month in which the Quran was revealed as guidance for mankind',
      },
      {
        title: 'درود ابراہیمی',
        source: 'صحیح بخاری، کتاب الصلاۃ',
        urduMeaning: 'نبی ﷺ پر درود پڑھنا اللہ کا حکم ہے اور ملائکہ کا عمل ہے',
        englishMeaning: 'Sending blessings upon the Prophet is commanded by Allah and practised by His angels',
      },
      {
        title: 'توبہ و استغفار',
        source: 'سورۃ البقرہ ۲:۲۲۲',
        urduMeaning: 'اللہ تعالیٰ توبہ کرنے والوں سے محبت فرماتا ہے',
        englishMeaning: 'Allah loves those who sincerely repent and turn back to Him',
      },
      {
        title: 'ماں کے قدموں تلے جنت',
        source: 'سنن نسائی؛ سنن ابن ماجہ',
        urduMeaning: 'جنت ماں کے قدموں تلے ہے — ماں کی خدمت سب سے بڑی عبادت ہے',
        englishMeaning: 'Paradise lies at the feet of mothers',
      },
      {
        title: 'صبر اور اللہ کی معیت',
        source: 'سورۃ البقرہ ۲:۱۵۳',
        urduMeaning: 'اللہ تعالیٰ صبر کرنے والوں کے ساتھ ہے',
        englishMeaning: 'Indeed, Allah is with the patient',
      },
      {
        title: 'زکوٰۃ — فرض صدقہ',
        source: 'سورۃ التوبہ ۹:۶۰',
        urduMeaning: 'زکوٰۃ ادا کرنا مال کو پاک کرتا ہے اور معاشرے میں برکت لاتا ہے',
        englishMeaning: 'Zakat purifies wealth and spreads blessing throughout the community',
      },
      {
        title: 'رمضان میں خاص عبادات',
        source: 'صحیح بخاری و مسلم',
        urduMeaning: 'رمضان میں تراویح، تہجد اور اعتکاف اللہ سے قربت کے بہترین ذرائع ہیں',
        englishMeaning: 'Tarawih, Tahajjud, and I\'tikaf in Ramadan are the finest means of drawing close to Allah',
      },
      {
        title: 'دعا — مومن کا ہتھیار',
        source: 'مستدرک الحاکم؛ سنن ابو داود',
        urduMeaning: 'دعا عبادت کی روح ہے اور اللہ اپنے بندوں کی دعا کو پسند فرماتا ہے',
        englishMeaning: "Du'a is the essence of worship; Allah loves it when His servants call upon Him",
      },
    ],

    poetry: [
      {
        title: 'خودی کو کر بلند',
        poet: 'علامہ محمد اقبال',
        era: 'جدید دور، ۱۹۳۲ء',
        meaning: "Raise your self so high that before every decree of fate, God Himself asks: 'What is your wish?' Iqbal's call to spiritual elevation and the development of the self (khudi) — the core of his philosophy.",
      },
      {
        title: 'ہزاروں سال نرگس',
        poet: 'علامہ محمد اقبال',
        era: 'جدید دور',
        meaning: "The narcissus weeps for centuries in the garden, longing for a seeing eye to witness its beauty. Iqbal reflects on the rarity of visionaries (deedawar) — those who can truly perceive spiritual reality.",
      },
      {
        title: 'دل ڈھونڈتا ہے',
        poet: 'مرزا اسد اللہ خاں غالب',
        era: 'مغلیہ دور، ۱۸۵۰ء کے لگ بھگ',
        meaning: 'The heart searches again for those leisurely days and nights — sitting lost in the thought of the beloved. Ghalib expresses romantic longing and nostalgic reverie with characteristic elegance and depth.',
      },
      {
        title: 'ہم کو ان سے وفا کی ہے امید',
        poet: 'مرزا اسد اللہ خاں غالب',
        era: 'مغلیہ دور',
        meaning: 'We hope for loyalty from those who do not even understand what loyalty means. Ghalib uses bittersweet irony to describe unrequited love and the tragedy of misplaced devotion.',
      },
      {
        title: 'مجھ سے پہلی سی محبت',
        poet: 'فیض احمد فیض',
        era: 'جدید دور، ۱۹۵۲ء',
        meaning: 'Faiz asks his beloved not to demand the innocent love of youth, for he has seen the world\'s pain and can no longer see only her face. Love now coexists with social consciousness and collective suffering.',
      },
      {
        title: 'آج بازار میں پابجولاں چلو',
        poet: 'فیض احمد فیض',
        era: 'جدید دور، ۱۹۵۸ء',
        meaning: "Walk into the marketplace in chains — a weeping eye and a troubled soul are not enough. Written during political imprisonment, Faiz calls for courageous, visible resistance against oppression and injustice.",
      },
      {
        title: 'ستاروں سے آگے',
        poet: 'علامہ محمد اقبال',
        era: 'جدید دور',
        meaning: "Beyond the stars, there are more worlds still — and more tests of love await you. Iqbal urges the believer to transcend complacency and reach for infinite spiritual and intellectual horizons beyond the visible.",
      },
      {
        title: 'تم مرے پاس ہوتے ہو گویا',
        poet: 'میر تقی میر',
        era: 'اٹھارہویں صدی، مغلیہ دور',
        meaning: "It is as if you are with me when no one else is around. Mir captures the profound paradox of love — the beloved's presence felt most intensely in their very absence and silence.",
      },
      {
        title: 'پرندے شاخوں پر',
        poet: 'پروین شاکر',
        era: 'جدید دور، ۱۹۷۰ء کی دہائی',
        meaning: 'Birds sit silently on branches; the entire sky is still and quiet. Parveen Shakir uses delicate nature imagery to evoke a moment of reflective stillness, inner longing, and quiet emotion.',
      },
      {
        title: 'یہ جذبے کا عالم',
        poet: 'پروین شاکر',
        era: 'جدید دور',
        meaning: "Is this a state of intense feeling, or the heart speaking? What a night has arrived in the season of love. Parveen Shakir evokes the overwhelming intensity of romantic feeling with her characteristic sensitivity.",
      },
      {
        title: 'جب تک زندہ ہوں',
        poet: 'ناصر کاظمی',
        era: 'جدید دور، ۱۹۵۰ء کی دہائی',
        meaning: 'As long as I live, there is desire and longing in my heart — and when I die, what then? Nasir Kazmi contemplates the fleeting nature of human yearning and the silence that inevitably follows.',
      },
      {
        title: 'نہیں تیری تقدیر میں',
        poet: 'احمد فراز',
        era: 'جدید دور، ۱۹۷۰ء',
        meaning: 'It was not in your fate — that night which my dreams had imagined for us. Ahmad Faraz mourns the gap between what was deeply longed for and what fate ultimately delivered.',
      },
      {
        title: 'بن کے مٹی خاک میں مل جائیں گے',
        poet: 'احمد فراز',
        era: 'جدید دور',
        meaning: "Turning to dust we shall merge into the earth — and this garden of life will endure. Ahmad Faraz reflects on human mortality against the eternal backdrop of nature's perpetual beauty and continuity.",
      },
    ],
  },

  arabic: {
    islamic: [
      {
        title: 'البسملة',
        source: 'سورة الفاتحة ١:١',
        englishMeaning: 'In the name of Allah, the Most Gracious, the Most Merciful',
        urduMeaning: 'اللہ کے نام سے شروع جو بڑا مہربان نہایت رحم والا ہے',
        context: 'Recited before every chapter of the Quran (except At-Tawbah) and before every lawful action. It is the most frequently spoken phrase by Muslims worldwide.',
      },
      {
        title: 'الفاتحة — آيات ٢-٤',
        source: 'سورة الفاتحة ١:٢-٤',
        englishMeaning: 'All praise is for Allah, Lord of all worlds, the Most Gracious, the Most Merciful, Master of the Day of Judgment',
        urduMeaning: 'تمام تعریفیں اللہ کے لیے ہیں — رحمن و رحیم، روزِ جزا کا مالک',
        context: 'These verses are recited in every unit (rak\'ah) of every prayer, making Al-Fatiha the most recited passage in Islamic worship across the world.',
      },
      {
        title: 'الفاتحة — آيات ٥-٧',
        source: 'سورة الفاتحة ١:٥-٧',
        englishMeaning: 'You alone we worship and You alone we ask for help. Guide us to the straight path — the path of those You have blessed, not those who earned anger or went astray',
        urduMeaning: 'ہم صرف تیری عبادت کرتے ہیں اور صرف تجھ سے مدد مانگتے ہیں — ہمیں سیدھا راستہ دکھا',
        context: "This completes Surah Al-Fatiha, establishing the believer's covenant with Allah — worship and humility in exchange for divine guidance toward the straight path.",
      },
      {
        title: 'سورة الإخلاص',
        source: 'سورة الإخلاص ١١٢:١-٤',
        englishMeaning: 'Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. And there is none comparable to Him',
        urduMeaning: 'کہو: وہ اللہ ایک ہے — اللہ بے نیاز ہے — نہ اس کی اولاد ہے نہ وہ کسی کی اولاد — اس کا کوئی ہمسر نہیں',
        context: 'The Prophet (PBUH) said Surah Al-Ikhlas equals one-third of the Quran in reward. It is recited in daily prayers, for protection, and to affirm the absolute oneness of Allah.',
      },
      {
        title: 'التسبيح العظيم',
        source: 'صحيح البخاري، كتاب الدعوات',
        englishMeaning: 'Glory be to Allah and His is the Praise; Glory be to Allah the Magnificent',
        urduMeaning: 'اللہ پاک ہے اپنی تعریف کے ساتھ؛ اللہ بہت عظیم ہے',
        context: 'The Prophet (PBUH) said these two phrases are light on the tongue, heavy on the Scale of deeds, and beloved to the Most Merciful — making them among the most rewarding words of remembrance.',
      },
      {
        title: 'أفضل الذكر — التهليل الكامل',
        source: 'صحيح البخاري ومسلم',
        englishMeaning: 'There is no god but Allah alone, with no partner. His is the dominion and all praise belongs to Him, and He has power over all things',
        urduMeaning: 'اللہ کے سوا کوئی معبود نہیں، تنہا بلا شریک — اسی کی بادشاہی اور اسی کی تعریف — وہ ہر چیز پر قادر ہے',
        context: 'The Prophet (PBUH) said reciting this 100 times daily earns the reward equivalent to freeing ten slaves, earns 100 good deeds, and expiates 100 sins.',
      },
      {
        title: 'الصلاة الإبراهيمية',
        source: 'صحيح البخاري، كتاب الصلاة',
        englishMeaning: 'O Allah, send blessings upon Muhammad and upon the family of Muhammad, just as You sent blessings upon Ibrahim and the family of Ibrahim',
        urduMeaning: 'اے اللہ! رحمت نازل فرما محمد ﷺ اور آل محمد پر جیسے تو نے ابراہیم اور آل ابراہیم پر رحمت نازل فرمائی',
        context: 'This is the Durood Ibrahim recited in the tashahhud of every prayer. The Prophet (PBUH) said Allah sends ten blessings upon the person who recites salawat upon him once.',
      },
      {
        title: 'دعاء خير الدنيا والآخرة',
        source: 'سورة البقرة ٢:٢٠١',
        englishMeaning: 'Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire',
        urduMeaning: 'اے ہمارے رب! ہمیں دنیا میں بھی بھلائی دے اور آخرت میں بھی — اور آگ کے عذاب سے بچا',
        context: "Called 'the comprehensive dua,' the Prophet (PBUH) would frequently make this supplication. It covers all of a believer's needs — success in this world and salvation in the next.",
      },
      {
        title: 'الاستعاذة — التعوذ من الشيطان',
        source: 'سورة النحل ١٦:٩٨',
        englishMeaning: 'I seek refuge in Allah from the accursed Satan',
        urduMeaning: 'میں اللہ کی پناہ مانگتا ہوں مردود شیطان سے',
        context: 'Recited before beginning any Quranic recitation. The Quran commands believers to seek Allah\'s refuge from Shaytan before reading, protecting them from distraction and spiritual harm.',
      },
      {
        title: 'دعاء الجامع للمغفرة والهداية',
        source: 'صحيح مسلم؛ سنن أبي داود',
        englishMeaning: 'O Allah, forgive me, have mercy on me, guide me, grant me well-being, and provide for me',
        urduMeaning: 'اے اللہ! مجھے معاف فرما، مجھ پر رحم کر، مجھے ہدایت دے، مجھے عافیت دے اور مجھے رزق دے',
        context: "The Prophet (PBUH) taught these seven comprehensive requests as a supplication covering all of a believer's spiritual and worldly needs in a few powerful words.",
      },
      {
        title: 'حسبنا الله ونعم الوكيل',
        source: 'سورة آل عمران ٣:١٧٣',
        englishMeaning: 'Allah is sufficient for us, and He is the best Disposer of affairs; the best Protector and the best Helper',
        urduMeaning: 'ہمارے لیے اللہ کافی ہے اور وہ بہترین کارساز ہے — بہترین مولیٰ اور بہترین مددگار',
        context: "Said by Ibrahim (AS) when thrown into the fire and by Muhammad (PBUH) after the Battle of Uhud. Reciting this in times of difficulty invites Allah's protection and care.",
      },
      {
        title: 'إن مع العسر يسرا',
        source: 'سورة الشرح ٩٤:٥-٦',
        englishMeaning: 'Verily, with hardship comes ease. Verily, with hardship comes ease',
        urduMeaning: 'بے شک مشکل کے ساتھ آسانی ہے — بے شک مشکل کے ساتھ آسانی ہے',
        context: "Allah repeats this promise twice in two consecutive verses, reassuring the Prophet (PBUH) and all believers that every hardship carries within it the seed of relief and ease.",
      },
      {
        title: 'الفرج والرزق بالتقوى',
        source: 'سورة الطلاق ٦٥:٢-٣',
        englishMeaning: 'Whoever fears Allah, He will make for them a way out, and will provide for them from where they do not expect',
        urduMeaning: 'جو اللہ سے ڈرتا ہے — اللہ اس کے لیے راستہ نکال دیتا ہے اور وہاں سے رزق دیتا ہے جہاں سے وہ گمان بھی نہیں کرتا',
        context: 'One of the most hope-inspiring verses in the Quran. Taqwa (God-consciousness) is promised to unlock provision and solutions from completely unexpected sources.',
      },
      {
        title: 'دعاء موسى عليه السلام',
        source: 'سورة طه ٢٠:٢٥-٢٨',
        englishMeaning: 'My Lord, expand my chest, ease my task, and untie the knot from my tongue so that people may understand my speech',
        urduMeaning: 'اے میرے رب! میرا سینہ کھول دے، میرا کام آسان کر، اور میری زبان کی گرہ کھول دے تاکہ لوگ میری بات سمجھ سکیں',
        context: "This dua of Prophet Musa (AS) is recited before public speaking, giving presentations, or beginning any difficult task requiring clarity, confidence, and divine assistance.",
      },
      {
        title: 'دعاء العفو والعافية',
        source: 'سنن الترمذي وابن ماجه',
        englishMeaning: 'O Allah, I ask You for pardon and well-being in this world and in the Hereafter',
        urduMeaning: 'اے اللہ! میں تجھ سے دنیا اور آخرت میں عفو اور عافیت مانگتا ہوں',
        context: "The Prophet (PBUH) said no supplication is dearer to him than asking for 'afiyah (comprehensive well-being in health, faith, family, and all affairs).",
      },
      {
        title: 'تسبيح كفارة المجلس',
        source: 'سنن الترمذي؛ سنن أبي داود',
        englishMeaning: 'Glory be to You, O Allah, and Yours is the praise. I testify there is no god but You. I seek Your forgiveness and I repent to You',
        urduMeaning: 'تو پاک ہے اے اللہ، تیری حمد ہو — میں گواہی دیتا ہوں کہ تیرے سوا کوئی معبود نہیں — میں تجھ سے مغفرت مانگتا اور توبہ کرتا ہوں',
        context: "Recited at the end of a gathering. The Prophet (PBUH) taught it as kaffarah (expiation) for any idle or improper speech that may have occurred during the session.",
      },
      {
        title: 'آية الكرسي',
        source: 'سورة البقرة ٢:٢٥٥',
        englishMeaning: "Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep — to Him belongs all that is in the heavens and the earth",
        urduMeaning: 'اللہ — اس کے سوا کوئی معبود نہیں، وہ ہمیشہ زندہ ہے، سب کو قائم رکھنے والا — نہ اسے اونگھ آتی ہے نہ نیند',
        context: 'The greatest verse of the Quran. Reciting Ayatul Kursi after every prayer is said to earn paradise, and before sleep it provides divine protection throughout the night.',
      },
    ],
  },

  persian: {
    poetry: [
      {
        title: 'بشنو این نی — آغاز مثنوی',
        poet: 'مولانا جلال الدین رومی',
        era: 'قرن سیزدهم میلادی (۱۲۰۷–۱۲۷۳)',
        englishMeaning: "Listen to the reed flute, how it tells a tale of separations — from the reed bed my complaint of longing arises. Rumi opens the Masnavi with the soul's yearning to return to its divine origin.",
      },
      {
        title: 'آتش عشق',
        poet: 'مولانا جلال الدین رومی',
        era: 'قرن سیزدهم میلادی',
        englishMeaning: 'The fire of love has fallen into the reed — the bubbling of love has fallen into the wine. Rumi uses fire and ferment as metaphors for divine love\'s transformative, all-consuming power.',
      },
      {
        title: 'الا یا ایها الساقی — آغاز دیوان حافظ',
        poet: 'خواجه شمس‌الدین محمد حافظ شیرازی',
        era: 'قرن چهاردهم میلادی (۱۳۲۵–۱۳۸۹)',
        englishMeaning: "Come, O cupbearer, pass the cup and offer it — for love seemed easy at first, but difficulties arose. The opening verse of Hafez's Divan beautifully blends mystical longing with earthly imagery.",
      },
      {
        title: 'حافظا در کنج فقر',
        poet: 'حافظ شیرازی',
        era: 'قرن چهاردهم میلادی',
        englishMeaning: 'Hafez, in the corner of poverty and dark nights — as long as prayer and Quran recitation are your devotion, do not grieve. A counsel of spiritual contentment over worldly wealth.',
      },
      {
        title: 'بوی بهبود',
        poet: 'حافظ شیرازی',
        era: 'قرن چهاردهم میلادی',
        englishMeaning: 'I sense the fragrance of improvement in the world\'s affairs — joy has come with the flower and the morning breeze. Hafez expresses spiritual optimism and hope through gentle nature imagery.',
      },
      {
        title: 'بنی آدم — سرود آدمیت',
        poet: 'شیخ مصلح‌الدین سعدی شیرازی',
        era: 'قرن سیزدهم میلادی (۱۲۱۰–۱۲۹۲)',
        englishMeaning: "The children of Adam are members of one body, created from the same essence. This verse — inscribed at the United Nations — calls for universal human solidarity and compassion.",
      },
      {
        title: 'چو عضوی به درد',
        poet: 'سعدی شیرازی',
        era: 'قرن سیزدهم میلادی',
        englishMeaning: "When one member of the body suffers, the others cannot rest in peace. Saadi continues his verse on human unity — the suffering of any one person demands the compassion and response of all.",
      },
      {
        title: 'آدمی در عالم خاکی',
        poet: 'حافظ شیرازی',
        era: 'قرن چهاردهم میلادی',
        englishMeaning: 'A true human being is not easily found in this earthly world — another world must be built and a new kind of human being created anew. Hafez reflects on the rarity of genuine spiritual humanity.',
      },
      {
        title: 'هر که آمد عمارت نو ساخت',
        poet: 'حکیم عمر خیام نیشابوری',
        era: 'قرن یازدهم میلادی (۱۰۴۸–۱۱۳۱)',
        englishMeaning: "Whoever came, built a new structure and then departed — and made others stumble who came after. Khayyam meditates on the transience of all human achievement and the impermanence of worldly ambition.",
      },
      {
        title: 'خیام اگر ز باده مستی',
        poet: 'حکیم عمر خیام نیشابوری',
        era: 'قرن یازدهم میلادی',
        englishMeaning: "Khayyam, if you are intoxicated with wine, be happy — if you sit with a moon-faced beloved, be happy. Khayyam uses wine as a symbol for spiritual absorption and living fully in the present moment.",
      },
      {
        title: 'گر مرد رهی',
        poet: 'فریدالدین عطار نیشابوری',
        era: 'قرن دوازدهم میلادی (۱۱۴۵–۱۲۲۱)',
        englishMeaning: "If you are a true traveler of the spiritual path, you must walk through blood — you must fall headlong and broken. Attar describes the demanding, self-sacrificing journey of the sincere seeker.",
      },
    ],
  },
}
