/**
 * Tool registry — single source of truth for all Typely tools.
 * Adding a new tool = adding one object here.
 * Nav, landing cards, related tools, breadcrumbs, and sitemap all read from this array.
 */

/** Category display order and labels */
export const TOOL_CATEGORIES = [
  { id: 'typing',    label: '⌨️ Typing & Productivity' },
  { id: 'writing',   label: '✍️ Writing Tools' },
  { id: 'language',  label: '🌍 Language & Input' },
  { id: 'finance',   label: '💰 Finance & Investing' },
  { id: 'travel',    label: '✈️ Travel & Recreation' },
  { id: 'health',    label: '🏥 Health & Wellness' },
  { id: 'developer', label: '🛠️ Developer Tools' },
  { id: 'education', label: '🎓 Education & Teaching' },
  { id: 'legal',     label: '⚖️ Legal & Research' },
  { id: 'business',  label: '🏢 Business & Field Work' },
  { id: 'security',  label: '🔒 Security & Privacy' },
]

export const TOOLS = [
  {
    id: 'typing-tutor',
    name: 'Typing Tutor',
    tagline: 'Test & improve your typing speed',
    description: 'Personalized typing practice with weak-key detection, multiple languages, and real-time feedback.',
    icon: '⌨️',
    path: '/',
    color: '#06b6d4',
    category: 'typing',
    tags: ['typing', 'speed', 'accuracy', 'wpm'],
    related: ['word-counter', 'text-cleaner'],
    isHome: true,
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    tagline: 'Analyze any text instantly',
    description: 'Count words, characters, sentences, and paragraphs. Get readability scores and keyword density — all in your browser.',
    icon: '📊',
    path: '/tools/word-counter',
    color: '#8b5cf6',
    category: 'writing',
    tags: ['writing', 'analysis', 'word count', 'readability'],
    related: ['text-cleaner', 'doc-composer'],
  },
  {
    id: 'text-cleaner',
    name: 'Text Formatter',
    tagline: 'Clean and format text in one click',
    description: 'Remove extra spaces, fix capitalization, convert case, strip formatting — paste and clean instantly.',
    icon: '✨',
    path: '/tools/text-cleaner',
    color: '#10b981',
    category: 'writing',
    tags: ['formatting', 'cleaning', 'case conversion'],
    related: ['word-counter', 'doc-composer'],
  },
  {
    id: 'doc-composer',
    name: 'Doc Composer',
    tagline: 'Create professional documents instantly',
    description: 'Fill smart templates for CVs, cover letters, emails, and contracts. Export to PDF or Word — no internet needed.',
    icon: '📄',
    path: '/tools/doc-composer',
    color: '#3b82f6',
    category: 'writing',
    tags: ['documents', 'pdf', 'cv', 'templates', 'freelancing'],
    related: ['word-counter', 'text-cleaner'],
  },
  {
    id: 'urdu-keyboard',
    name: 'Urdu Keyboard',
    tagline: 'Type Urdu phonetically on any device',
    description: 'Type Urdu using English phonetics — no Urdu keyboard needed. Copy and use anywhere.',
    icon: '🌍',
    path: '/tools/urdu-keyboard',
    color: '#f59e0b',
    category: 'language',
    tags: ['urdu', 'keyboard', 'phonetic', 'pakistan'],
    related: ['typing-tutor', 'doc-composer'],
  },
  {
    id: 'tax-calculator',
    name: 'Pakistan Tax Calculator',
    tagline: 'Estimate your income tax & find savings',
    description: 'Calculate your salary tax under Finance Act 2025. See your tax shields (VPS, charity, health) and how much you can legally save.',
    icon: '🧮',
    path: '/tools/tax-calculator',
    color: '#f97316',
    category: 'finance',
    tags: ['tax', 'pakistan', 'salary', 'fbr', '2025', 'income tax'],
    related: ['doc-composer', 'word-counter'],
  },
  {
    id: 'text-encryptor',
    name: 'Text Encryptor',
    tagline: 'Encrypt private messages locally',
    description: 'AES-256 encryption powered by your browser. Your text and password never leave your device.',
    icon: '🔒',
    path: '/tools/text-encryptor',
    color: '#ef4444',
    category: 'security',
    tags: ['security', 'encryption', 'privacy'],
    related: ['text-cleaner', 'doc-composer'],
  },
  // ── Travel & Recreation ──
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    tagline: 'Live exchange rates for travelers',
    description: 'Convert between 30+ currencies with live rates. Great for trip budgeting — PKR, USD, GBP, AED and more.',
    icon: '💱',
    path: '/tools/currency-converter',
    color: '#06b6d4',
    category: 'travel',
    tags: ['currency', 'exchange', 'travel', 'pakistan', 'pkr'],
    related: ['budget-splitter', 'tax-calculator'],
  },
  {
    id: 'packing-list',
    name: 'Smart Packing List',
    tagline: 'Weather-aware packing for any trip',
    description: 'Enter your destination and travel dates. We fetch the forecast and generate a tailored packing list — no guesswork.',
    icon: '🧳',
    path: '/tools/packing-list',
    color: '#f59e0b',
    category: 'travel',
    tags: ['travel', 'packing', 'weather', 'checklist'],
    related: ['currency-converter', 'budget-splitter'],
  },
  {
    id: 'budget-splitter',
    name: 'Trip Budget Splitter',
    tagline: 'Split group travel expenses fairly',
    description: 'Add trip expenses, assign payers, and instantly see the minimum transactions to settle up — no more awkward maths.',
    icon: '🤝',
    path: '/tools/budget-splitter',
    color: '#8b5cf6',
    category: 'travel',
    tags: ['travel', 'budget', 'expenses', 'group', 'split'],
    related: ['currency-converter', 'packing-list'],
  },
  // ── Health & Wellness ──
  {
    id: 'drug-checker',
    name: 'Drug Interaction Checker',
    tagline: 'Check medication interactions instantly',
    description: 'Enter your medications and supplements to see potential interactions — powered by the US National Library of Medicine (free, no data uploaded).',
    icon: '💊',
    path: '/tools/drug-checker',
    color: '#10b981',
    category: 'health',
    tags: ['health', 'medication', 'drugs', 'interactions', 'pharmacy'],
    related: ['symptom-tracker'],
  },
  {
    id: 'symptom-tracker',
    name: 'Symptom Context Tracker',
    tagline: 'Log symptoms with real-world context',
    description: 'Track how you feel alongside local weather, air pressure and temperature changes. Non-alarmist — understands your environment, not just your pain.',
    icon: '🩺',
    path: '/tools/symptom-tracker',
    color: '#f97316',
    category: 'health',
    tags: ['health', 'symptoms', 'wellness', 'weather', 'tracker'],
    related: ['drug-checker'],
  },
  // ── Developer Tools ──────────────────────────────────────────────
  {
    id: 'data-transformer',
    name: 'Privacy-First Data Transformer',
    tagline: 'Convert JSON, CSV & TSV 100% client-side',
    description: 'Transform data between JSON, CSV and TSV formats entirely in your browser — nothing leaves your machine. Includes a De-identifier toggle that auto-detects and masks emails, API keys and IP addresses.',
    icon: '🔄',
    path: '/tools/data-transformer',
    color: '#6366f1',
    category: 'developer',
    tags: ['json', 'csv', 'tsv', 'converter', 'privacy', 'developer'],
    related: ['config-converter', 'mock-data'],
  },
  {
    id: 'markdown-scraper',
    name: 'LLM-Ready Markdown Scraper',
    tagline: 'Turn any URL into clean Markdown for AI',
    description: 'Paste a URL or raw HTML and get clean, token-efficient Markdown optimised for LLM context windows. Generates a Table of Contents and strips code comments to keep output lean.',
    icon: '📄',
    path: '/tools/markdown-scraper',
    color: '#8b5cf6',
    category: 'developer',
    tags: ['markdown', 'scraper', 'llm', 'ai', 'html', 'developer'],
    related: ['data-transformer', 'log-analyzer'],
  },
  {
    id: 'log-analyzer',
    name: 'Smart Log Analyzer',
    tagline: 'Cluster errors and copy unique traces for AI',
    description: 'Paste raw server logs and instantly see errors grouped by pattern. The "Copy for AI" button extracts only unique stack traces, saving you from manually hunting through gigabytes of noise.',
    icon: '🪵',
    path: '/tools/log-analyzer',
    color: '#f59e0b',
    category: 'developer',
    tags: ['logs', 'errors', 'debugging', 'ai', 'devtools', 'developer'],
    related: ['markdown-scraper', 'data-transformer'],
  },
  {
    id: 'config-converter',
    name: 'Config Polyglot Converter',
    tagline: 'Convert .env ↔ JSON ↔ YAML ↔ TOML instantly',
    description: 'Drag-and-drop or paste any config file and convert between .env, JSON, YAML and TOML formats instantly in your browser — no uploads, no servers.',
    icon: '⚙️',
    path: '/tools/config-converter',
    color: '#0ea5e9',
    category: 'developer',
    tags: ['config', 'env', 'yaml', 'json', 'toml', 'converter', 'developer'],
    related: ['data-transformer', 'mock-data'],
  },
  {
    id: 'mock-data',
    name: 'Mock Data Generator',
    tagline: 'Generate bulk test data from a simple schema',
    description: 'Define a quick schema (name, type, constraints) and generate thousands of unique rows in JSON or CSV. Edge Case mode purposely inserts nulls, zeros and special characters to stress-test your code.',
    icon: '🎲',
    path: '/tools/mock-data',
    color: '#ec4899',
    category: 'developer',
    tags: ['mock', 'data', 'testing', 'json', 'csv', 'generator', 'developer'],
    related: ['data-transformer', 'config-converter'],
  },
  // ── Education & Teaching ────────────────────────────────────────
  {
    id: 'student-groups',
    name: 'Student Group Randomizer',
    tagline: 'Balance skill levels across classroom groups',
    description: 'Paste your class roster with skill levels and instantly generate balanced groups that mix ability levels — no manual sorting, no favoritism.',
    icon: '👥',
    path: '/tools/student-groups',
    color: '#ec4899',
    category: 'education',
    tags: ['education', 'teaching', 'classroom', 'groups', 'students'],
    related: [],
  },
  // ── Legal & Research ───────────────────────────────────────────
  {
    id: 'timeline-builder',
    name: 'Contextual Timeline Builder',
    tagline: 'Turn scattered dates into a visual timeline',
    description: 'Paste events with dates in any format — emails, notes, bullet points. Auto-extracts dates and renders an interactive, exportable visual timeline for reports, cases, or projects.',
    icon: '📅',
    path: '/tools/timeline-builder',
    color: '#06b6d4',
    category: 'legal',
    tags: ['timeline', 'legal', 'research', 'dates', 'visualization'],
    related: [],
  },
  // ── Business & Field Work ──────────────────────────────────────
  {
    id: 'position-size-calc',
    name: 'Position Size Calculator',
    tagline: 'Risk exactly 1% — never over-leverage again',
    description: 'Enter your account size, risk percentage, entry price and stop-loss. Instantly see how many shares to buy so you never risk more than you intend on any trade.',
    icon: '📊',
    path: '/tools/position-size-calc',
    color: '#10b981',
    category: 'business',
    tags: ['trading', 'stocks', 'risk', 'position', 'calculator', 'finance'],
    related: ['property-comp'],
  },
  {
    id: 'voice-invoice',
    name: 'Voice-to-Invoice',
    tagline: 'Speak your job — get a formatted invoice',
    description: 'Speak your work items while driving to the next job. The tool transcribes your words into clean, structured line-item invoice rows ready to download or copy into your billing software.',
    icon: '🎙️',
    path: '/tools/voice-invoice',
    color: '#f97316',
    category: 'business',
    tags: ['voice', 'invoice', 'hvac', 'field', 'billing', 'speech'],
    related: ['position-size-calc'],
  },
  {
    id: 'property-comp',
    name: 'Property Comp Adjuster',
    tagline: 'Toggle features to calculate valuation delta',
    description: 'Compare a subject property against a comparable sale. Toggle differences in bedrooms, bathrooms, square footage and garage — see the adjusted valuation impact instantly.',
    icon: '🏠',
    path: '/tools/property-comp',
    color: '#8b5cf6',
    category: 'business',
    tags: ['real estate', 'appraisal', 'property', 'valuation', 'calculator'],
    related: ['position-size-calc'],
  },
  {
    id: 'refrigerant-calc',
    name: 'Refrigerant Leak Calculator',
    tagline: 'EPA leak rate compliance in seconds',
    description: 'Enter your system charge and refrigerant added to instantly calculate the annual leak rate percentage and compare it against EPA thresholds — know if a mandatory repair is required.',
    icon: '❄️',
    path: '/tools/refrigerant-calc',
    color: '#0ea5e9',
    category: 'business',
    tags: ['hvac', 'refrigerant', 'epa', 'compliance', 'calculator'],
    related: ['voice-invoice'],
  },
]

/** Lookup a tool by id. */
export function getToolById(id) {
  return TOOLS.find((t) => t.id === id) || null
}

/** Get related tool objects for a given tool id. */
export function getRelatedTools(id) {
  const tool = getToolById(id)
  if (!tool) return []
  return (tool.related || []).map(getToolById).filter(Boolean)
}
