/**
 * Tool registry — single source of truth for all Typely tools.
 * Adding a new tool = adding one object here.
 * Nav, landing cards, related tools, breadcrumbs, and sitemap all read from this array.
 */

/** Category display order and labels */
export const TOOL_CATEGORIES = [
  { id: 'typing',      label: '⌨️ Typing & Learning' },
  { id: 'productivity',label: '⚡ Productivity' },
  { id: 'writing',     label: '✍️ Writing Tools' },
  { id: 'language',    label: '🌍 Language & Input' },
  { id: 'finance',     label: '💰 Finance & Investing' },
  { id: 'pakistan',    label: '🇵🇰 Pakistan Tools' },
  { id: 'travel',      label: '✈️ Travel & Recreation' },
  { id: 'health',      label: '🏥 Health & Wellness' },
  { id: 'developer',   label: '🛠️ Developer Tools' },
  { id: 'education',   label: '🎓 Education & Teaching' },
  { id: 'legal',       label: '⚖️ Legal & Research' },
  { id: 'business',    label: '🏢 Business & Field Work' },
  { id: 'security',    label: '🔒 Security & Privacy' },
  { id: 'pdf',         label: '📄 PDF Tools' },
]

export const TOOLS = [
  {
    id: 'typing-tutor',
    name: 'Typing Tutor',
    nameUrdu: 'ٹائپنگ ٹیوٹر',
    tagline: 'Test & improve your typing speed',
    taglineUrdu: 'ٹائپنگ کی رفتار جانچیں اور بہتر کریں',
    description: 'Personalized typing practice with weak-key detection, multiple languages, and real-time feedback.',
    icon: '⌨️',
    path: '/tools/typing-tutor',
    color: '#06b6d4',
    category: 'typing',
    tags: ['typing', 'speed', 'accuracy', 'wpm'],
    related: ['word-counter', 'text-cleaner'],
    features: ['Real-time WPM and accuracy feedback as you type', 'Weak-key drill targets your slowest letters', 'English, Urdu, Arabic, Kids and Custom text modes', 'XP, badges, leaderboard and multiplayer battles'],
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro — Focus Engine',
    nameUrdu: 'فوکس انجن — پوموڈورو',
    tagline: 'Deep work in 25-min sprints. Beat distraction. Get things done.',
    taglineUrdu: '۲۵ منٹ توجہ دیں، وقفہ لیں، ذہن تازہ رکھیں',
    description: 'A clean, distraction-free Pomodoro timer with Web Audio beeps, configurable durations, session history and a live countdown in your browser tab.',
    icon: '🍅',
    path: '/tools/pomodoro',
    color: '#ef4444',
    category: 'productivity',
    tags: ['productivity', 'focus', 'pomodoro', 'timer', 'study', 'work'],
    features: ['25/5/15 min work/short/long break cycles', 'Configurable durations (1–120 min)', 'Web Audio API beep — no CDN dependency', 'Session count + minutes focused tracked in localStorage'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    nameUrdu: 'الفاظ شمار کنندہ',
    tagline: 'Analyze any text instantly',
    taglineUrdu: 'کسی بھی متن کا فوری تجزیہ کریں',
    description: 'Count words, characters, sentences, and paragraphs. Get readability scores and keyword density — all in your browser.',
    icon: '📊',
    path: '/tools/word-counter',
    color: '#8b5cf6',
    category: 'writing',
    tags: ['writing', 'analysis', 'word count', 'readability'],
    related: ['text-cleaner', 'doc-composer'],
    features: ['Word, character, sentence and paragraph counts', 'Readability score (Flesch-Kincaid)', 'Keyword density for SEO', 'Estimated reading time'],
  },
  {
    id: 'text-cleaner',
    name: 'Text Formatter',
    nameUrdu: 'متن فارمیٹر',
    tagline: 'Clean and format text in one click',
    taglineUrdu: 'ایک کلک میں متن صاف اور فارمیٹ کریں',
    description: 'Remove extra spaces, fix capitalization, convert case, strip formatting — paste and clean instantly.',
    icon: '✨',
    path: '/tools/text-cleaner',
    color: '#10b981',
    category: 'writing',
    tags: ['formatting', 'cleaning', 'case conversion'],
    related: ['word-counter', 'doc-composer'],
    features: ['Remove extra spaces and blank lines', 'Fix capitalisation: title case, UPPER, lower, sentence', 'Strip HTML tags and Markdown formatting', 'Convert smart quotes to straight quotes'],
  },
  {
    id: 'doc-composer',
    name: 'Doc Composer',
    nameUrdu: 'دستاویز ساز',
    tagline: 'Create professional documents instantly',
    taglineUrdu: 'پیشہ ورانہ دستاویزات فوری بنائیں',
    description: 'Fill smart templates for CVs, cover letters, emails, and contracts. Export to PDF or Word — no internet needed.',
    icon: '📄',
    path: '/tools/doc-composer',
    color: '#3b82f6',
    category: 'writing',
    tags: ['documents', 'pdf', 'cv', 'templates', 'freelancing'],
    related: ['word-counter', 'text-cleaner'],
    features: ['Smart templates: CVs, cover letters, invoices, contracts', 'Fill-in-the-blank guided form fields', 'Export to PDF or Word (.docx)', 'No internet required -- fully browser-based'],
  },
  {
    id: 'urdu-keyboard',
    name: 'Urdu Keyboard',
    nameUrdu: 'اردو کی بورڈ',
    tagline: 'Type Urdu phonetically on any device',
    taglineUrdu: 'کسی بھی ڈیوائس پر صوتی طریقے سے اردو ٹائپ کریں',
    description: 'Type Urdu using English phonetics — no Urdu keyboard needed. Copy and use anywhere.',
    icon: '🌍',
    path: '/tools/urdu-keyboard',
    color: '#f59e0b',
    category: 'language',
    tags: ['urdu', 'keyboard', 'phonetic', 'pakistan'],
    related: ['typing-tutor', 'doc-composer'],
    region: 'pk',
    features: ['Type Urdu using English phonetics on any device', 'No special keyboard or IME needed', 'One-click copy to clipboard', 'Supports common Urdu ligatures'],
  },
  {
    id: 'tax-calculator',
    name: 'Pakistan Tax Calculator',
    nameUrdu: 'پاکستان ٹیکس کیلکولیٹر',
    tagline: 'Estimate your income tax & find savings',
    taglineUrdu: 'آمدنی ٹیکس کا تخمینہ لگائیں اور بچت ڈھونڈیں',
    description: 'Calculate your salary tax under Finance Act 2025. See your tax shields (VPS, charity, health) and how much you can legally save.',
    icon: '🧮',
    path: '/tools/tax-calculator',
    color: '#f97316',
    category: 'pakistan',
    tags: ['tax', 'pakistan', 'salary', 'fbr', '2025', 'income tax'],
    related: ['tax-optimizer', 'doc-composer', 'word-counter'],
    region: 'pk',
    features: ['Pakistan salary tax under Finance Act 2025', 'Tax shields: VPS (Sec 63), Life Insurance (Sec 62), Charity (Sec 61)', 'Effective tax rate and monthly take-home', 'Filer and non-filer rate support'],
  },
  {
    id: 'loan-emi',
    name: 'Loan EMI Calculator',
    nameUrdu: 'قرض ای ایم آئی کیلکولیٹر',
    tagline: 'Monthly payments & full amortization for any loan',
    taglineUrdu: 'قرض کی ماہانہ قسط اور مکمل جدول',
    description: 'Calculate your monthly EMI, total payment, and interest cost for home, car or personal loans. Includes a full month-by-month amortization schedule.',
    icon: '🏦',
    path: '/tools/loan-emi',
    color: '#3b82f6',
    category: 'finance',
    tags: ['loan', 'emi', 'mortgage', 'car loan', 'interest', 'amortization', 'pakistan', 'finance'],
    related: ['tax-calculator', 'expense-analyzer', 'budget-splitter'],
    features: ['EMI formula: principal, rate, tenure', 'Full month-by-month amortization table', 'Principal vs interest breakdown bar chart', 'PKR and USD currency support'],
  },
  {
    id: 'salary-slip',
    name: 'Salary Slip Generator',
    nameUrdu: 'تنخواہ سلپ جنریٹر',
    tagline: 'Printable salary slip with FBR tax & EOBI',
    taglineUrdu: 'ایف بی آر ٹیکس اور ای او بی آئی کے ساتھ تنخواہ سلپ',
    description: 'Generate a professional printable salary slip with automatic FBR income tax estimation (Finance Act 2024-25) and EOBI deductions. No data ever leaves your device.',
    icon: '🧾',
    path: '/tools/salary-slip',
    color: '#10b981',
    category: 'pakistan',
    region: 'pk',
    tags: ['salary', 'payslip', 'salary slip', 'eobi', 'income tax', 'pakistan', 'hr', 'payroll'],
    related: ['tax-calculator', 'loan-emi', 'expense-analyzer'],
    features: ['EOBI auto-calc (employee 1%, employer 5%)', 'FBR 2024-25 income tax slab estimation', 'Printable A4 slip — print or save as PDF', 'Company info, designation, custom allowances'],
  },
  {
    id: 'world-time',
    name: 'World Time Converter',
    nameUrdu: 'عالمی وقت کنورٹر',
    tagline: 'Live clocks, time converter & best-meeting-time finder',
    taglineUrdu: 'لائیو گھڑیاں، وقت کنورٹر اور بہترین میٹنگ وقت',
    description: 'Live multi-city clocks with day/night indicators, working-hours highlighting, natural language time converter (supports Roman Urdu), 48-hour timeline slider, and best-time-to-meet finder for remote teams.',
    icon: '🌍',
    path: '/tools/world-time',
    color: '#06b6d4',
    category: 'productivity',
    tags: ['world clock', 'time zone', 'time converter', 'meeting time', 'freelancer', 'karachi', 'dubai', 'london', 'new york'],
    related: ['pomodoro', 'timeline-builder', 'currency-converter'],
    features: ['Live clocks for 20+ cities with day/night indicator', 'Natural language time converter (Roman Urdu supported)', '48-hour timeline slider — drag to see all time zones at once', 'Best Time to Meet finder for 2–4 cities'],
  },
  {
    id: 'voice-diary',
    name: 'Voice Diary',
    nameUrdu: 'وائس ڈائری',
    tagline: 'Speak or type your thoughts — private, offline diary',
    taglineUrdu: 'بولیں یا لکھیں — ذاتی آف لائن ڈائری',
    description: 'A private diary where you can record entries by speaking (Web Speech API) or typing. Supports English and Urdu voice input, mood tags, keyword search, and full text export. Nothing leaves your device.',
    icon: '🎙️',
    path: '/tools/voice-diary',
    color: '#ec4899',
    category: 'productivity',
    tags: ['diary', 'journal', 'voice', 'speech to text', 'urdu', 'notes', 'private'],
    related: ['daily-planner', 'habit-tracker', 'pomodoro'],
    features: ['Voice input via Web Speech API (English + Urdu)', 'Mood tags: 😊 😐 😔 😤 🙏', 'Full-text search across all entries', 'Export all entries as .txt file'],
  },
  {
    id: 'kameti',
    name: 'Kameti Tracker',
    nameUrdu: 'کمیٹی ٹریکر',
    tagline: 'Manage your savings committee — turns, payments & share link',
    taglineUrdu: 'اپنی کمیٹی منیج کریں — باری، ادائیگی اور شیئر لنک',
    description: 'Track a Pakistani-style savings committee (kameti/committee). Add members, set monthly contribution, auto-assign or drag-reorder turns, mark monthly payments, and share a read-only link with all participants.',
    icon: '🤝',
    path: '/tools/kameti',
    color: '#8b5cf6',
    category: 'pakistan',
    region: 'pk',
    tags: ['kameti', 'committee', 'chit fund', 'savings', 'pakistan', 'monthly', 'rotation'],
    related: ['loan-manager', 'loan-emi', 'expense-analyzer'],
    features: ['Add members, set contribution & start date', 'Drag-to-reorder turns or randomize', 'Mark monthly payments per member', 'Shareable read-only URL via base64 state'],
  },
  {
    id: 'daily-planner',
    name: 'Daily Planner',
    nameUrdu: 'روزانہ پلانر',
    tagline: 'Day-by-day task planner with priorities and weekly view',
    taglineUrdu: 'ترجیحات اور ہفتہ وار منظر کے ساتھ روزانہ ٹاسک پلانر',
    description: 'Plan your day with prioritized tasks, time slots, and categories. Navigate day-by-day, view your weekly completion grid, and copy pending tasks from yesterday — all saved locally.',
    icon: '📅',
    path: '/tools/daily-planner',
    color: '#3b82f6',
    category: 'productivity',
    tags: ['planner', 'todo', 'tasks', 'daily', 'schedule', 'productivity', 'checklist'],
    related: ['pomodoro', 'habit-tracker', 'voice-diary'],
    features: ['Day navigation with date picker', 'Priority (🔴🟡🟢) + time + category per task', 'Weekly 7-day completion grid', 'Copy yesterday\'s pending tasks in one click'],
  },
  {
    id: 'habit-tracker',
    name: 'Habit Tracker',
    nameUrdu: 'عادات ٹریکر',
    tagline: 'Build streaks with a GitHub-style habit heatmap',
    taglineUrdu: 'گٹ ہب طرز کے ہیٹ میپ کے ساتھ عادات بنائیں',
    description: 'Track daily habits with streak counters, a monthly heatmap calendar, and weekly bar charts. Add habits with custom emoji, color, and frequency. Archive old habits without losing history.',
    icon: '🔥',
    path: '/tools/habit-tracker',
    color: '#10b981',
    category: 'productivity',
    tags: ['habits', 'streak', 'tracker', 'heatmap', 'daily', 'goals', 'productivity'],
    related: ['daily-planner', 'pomodoro', 'voice-diary'],
    features: ['Tap-to-check circles for today\'s habits', 'Monthly heatmap calendar per habit', 'Current & longest streak calculation', 'Weekly day-of-week bar chart (last 30 days)'],
  },
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    nameUrdu: 'رنگ پیلیٹ جنریٹر',
    tagline: 'Generate harmonious color palettes with WCAG contrast check',
    taglineUrdu: 'WCAG کنٹراسٹ چیک کے ساتھ ہم آہنگ رنگ پیلیٹ بنائیں',
    description: 'Pick a seed color and generate complementary, triadic, analogous or monochromatic palettes. Includes WCAG AA/AAA contrast checker and export as CSS variables, JSON, or Tailwind config.',
    icon: '🎨',
    path: '/tools/color-palette',
    color: '#a855f7',
    category: 'developer',
    tags: ['color', 'palette', 'design', 'css', 'tailwind', 'wcag', 'accessibility', 'hex', 'rgb', 'hsl'],
    related: ['regex-tester', 'data-transformer', 'mock-data'],
    features: ['6 harmony modes: complementary, triadic, analogous…', 'Click any swatch to copy hex', 'WCAG AA/AAA contrast ratio checker', 'Export as CSS variables, JSON, or Tailwind config'],
  },
  {
    id: 'pk-id-tax-hub',
    name: 'Pakistan ID & Tax Hub',
    nameUrdu: 'پاکستان آئی ڈی اور ٹیکس',
    tagline: 'CNIC decoder · NTN/STRN validator · WHT rates · FBR calendar',
    taglineUrdu: 'شناختی کارڈ ڈیکوڈر · این ٹی این/ایس ٹی آر این · ود ہولڈنگ ٹیکس · ایف بی آر کیلنڈر',
    description: 'All-in-one Pakistan identity & tax reference: decode CNIC province/division/district, validate B-Form, NTN & STRN, check filer vs non-filer WHT rates, FBR deadlines, and full tax glossary.',
    icon: '🇵🇰',
    path: '/tools/pk-id-tax-hub',
    color: '#0ea5e9',
    category: 'pakistan',
    region: 'pk',
    tags: ['cnic', 'nadra', 'id card', 'ntn', 'strn', 'fbr', 'tax', 'filer', 'atl', 'wht', 'withholding', 'b-form', 'pakistan', 'identity', 'rto'],
    related: ['tax-calculator', 'salary-slip', 'tax-optimizer'],
    features: ['CNIC decoder: province, division, district, gender', 'NTN & STRN format validator with RTO decode', 'Filer vs non-filer WHT rate table (13 transaction types)', 'FBR tax deadlines calendar + 8-term glossary'],
  },
  {
    id: 'loan-manager',
    name: 'Loan Manager',
    nameUrdu: 'قرض مینیجر',
    tagline: 'Track all loans given and owed — with payment history',
    taglineUrdu: 'دیے اور لیے گئے تمام قرضوں کا حساب رکھیں',
    description: 'Keep track of every loan you\'ve given or borrowed. Record partial payments, see running balances, get overdue alerts, and mark loans as settled. All stored locally — nothing goes to any server.',
    icon: '💰',
    path: '/tools/loan-manager',
    color: '#f59e0b',
    category: 'finance',
    tags: ['loan', 'borrow', 'lend', 'debt', 'money', 'tracker', 'pakistan', 'finance'],
    related: ['kameti', 'loan-emi', 'expense-analyzer'],
    features: ['Two tabs: I Lent / I Borrowed', 'Record partial payments with running balance', 'Overdue indicator with days elapsed', 'Filter: All / Active / Settled, sort by amount or date'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    nameUrdu: 'ریجیکس ٹیسٹر',
    tagline: 'Live regex tester with match highlighting and replace mode',
    taglineUrdu: 'میچ ہائی لائٹنگ اور ریپلیس موڈ کے ساتھ لائیو ریجیکس ٹیسٹر',
    description: 'Test regular expressions live with inline match highlighting, capture group breakdown, and replace preview. Includes 8 common pattern shortcuts and flags reference.',
    icon: '🔍',
    path: '/tools/regex-tester',
    color: '#f97316',
    category: 'developer',
    tags: ['regex', 'regular expression', 'pattern', 'search', 'replace', 'developer', 'tools'],
    related: ['data-transformer', 'log-analyzer', 'color-palette'],
    features: ['Live match highlighting with capture groups', 'Replace mode with real-time preview', '8 common patterns: Email, URL, CNIC, PK Phone…', 'Copy pattern or all matches as JSON'],
  },
  {
    id: 'gold-price',
    name: 'Gold & Silver Calculator',
    nameUrdu: 'سونا چاندی کیلکولیٹر',
    tagline: 'Calculate gold & silver value with zakat — Pakistan rates',
    taglineUrdu: 'زکوٰۃ کے ساتھ سونے چاندی کی قیمت — پاکستانی نرخ',
    description: 'Calculate gold and silver value in tola, gram, masha, ratti, and troy oz. Supports 14K–24K purity, making charges, and Zakat calculation based on nisab. Enter today\'s sarafa bazar rate.',
    icon: '🥇',
    path: '/tools/gold-price',
    color: '#f59e0b',
    category: 'pakistan',
    region: 'pk',
    tags: ['gold', 'silver', 'tola', 'masha', 'ratti', 'zakat', 'nisab', 'pakistan', 'sarafa', 'jewellery'],
    related: ['loan-emi', 'tax-calculator', 'expense-analyzer'],
    features: ['Weight in tola, gram, masha, ratti, troy oz, kg', '24K / 22K / 21K / 18K / 14K purity selector', 'Zakat calculator with gold & silver nisab', 'Making charges + gold vs silver comparison'],
  },

  {
    id: 'tax-optimizer',
    name: 'Tax Shield Optimizer',
    nameUrdu: 'ٹیکس شیلڈ آپٹیمائزر',
    tagline: 'Find the exact split that maximises your tax credit',
    taglineUrdu: 'ٹیکس کریڈٹ زیادہ سے زیادہ کرنے کا بہترین طریقہ',
    description: 'Deterministic constraint solver for Pakistan tax shields. Enter salary + budget — it allocates optimally across VPS (Sec 63), Life Insurance (Sec 62) & Charity (Sec 61). Something AI cannot reliably do.',
    icon: '🧠',
    path: '/tools/tax-optimizer',
    color: '#10b981',
    category: 'pakistan',
    tags: ['tax', 'optimizer', 'vps', 'charity', 'insurance', 'pakistan', 'fbr', '2025', 'goal seek'],
    related: ['tax-calculator', 'expense-analyzer'],
    region: 'pk',
    features: ['Optimal VPS + insurance + charity allocation for your budget', 'Deterministic solver -- not AI guessing', 'Shows exact PKR saved for each scenario', 'Works for all income brackets under Finance Act 2025'],
  },
  {
    id: 'text-encryptor',
    name: 'Text Encryptor',
    nameUrdu: 'متن انکرپٹر',
    tagline: 'Encrypt private messages locally',
    taglineUrdu: 'نجی پیغامات مقامی طور پر خفیہ کریں',
    description: 'AES-256 encryption powered by your browser. Your text and password never leave your device.',
    icon: '🔒',
    path: '/tools/text-encryptor',
    color: '#ef4444',
    category: 'security',
    tags: ['security', 'encryption', 'privacy'],
    related: ['data-leak-detector', 'text-cleaner'],
    features: ['AES-256-GCM encryption entirely in your browser', 'Password-based key derivation (PBKDF2)', 'Encrypt and decrypt messages or notes', 'Key and text never leave your device'],
  },
  {
    id: 'data-leak-detector',
    name: 'Data Leak Detector',
    nameUrdu: 'ڈیٹا لیک ڈیٹیکٹر',
    tagline: 'Scan logs & configs for secrets before sharing',
    taglineUrdu: 'شیئر کرنے سے پہلے لاگز میں خفیہ معلومات تلاش کریں',
    description: 'Paste logs, configs, or API responses to instantly detect AWS keys, GitHub tokens, database URLs, PII, and more — entirely in your browser.',
    icon: '🛡️',
    path: '/tools/data-leak-detector',
    color: '#ef4444',
    category: 'security',
    tags: ['security', 'secrets', 'credentials', 'pii', 'leaks', 'devtools'],
    related: ['text-encryptor', 'log-analyzer', 'data-transformer'],
    features: ['Detects 50+ secret types: AWS keys, JWT, GitHub tokens, CNICs, IBANs', 'Severity colour-coding for each finding', 'One-click redacted safe copy', '100% client-side -- nothing leaves the browser'],
  },
  // ── Travel & Recreation ──
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    nameUrdu: 'کرنسی کنورٹر',
    tagline: 'Live exchange rates for travelers',
    taglineUrdu: 'مسافروں کے لیے لائیو شرح تبادلہ',
    description: 'Convert between 30+ currencies with live rates. Great for trip budgeting — PKR, USD, GBP, AED and more.',
    icon: '💱',
    path: '/tools/currency-converter',
    color: '#06b6d4',
    category: 'travel',
    tags: ['currency', 'exchange', 'travel', 'pakistan', 'pkr'],
    related: ['budget-splitter', 'tax-calculator'],
    features: ['Live exchange rates for 30+ currencies', 'PKR, USD, GBP, AED, SAR and more', 'Quick-swap between any two currencies', 'Works offline once loaded'],
  },
  {
    id: 'packing-list',
    name: 'Smart Packing List',
    nameUrdu: 'سفری سامان فہرست',
    tagline: 'Weather-aware packing for any trip',
    taglineUrdu: 'موسم کے مطابق سفری سامان باندھیں',
    description: 'Enter your destination and travel dates. We fetch the forecast and generate a tailored packing list — no guesswork.',
    icon: '🧳',
    path: '/tools/packing-list',
    color: '#f59e0b',
    category: 'travel',
    tags: ['travel', 'packing', 'weather', 'checklist'],
    related: ['currency-converter', 'budget-splitter'],
    features: ['Weather-smart packing suggestions for your destination and dates', 'Customisable categories: clothing, toiletries, documents, gear', 'Check off items as you pack', 'Save and reuse lists'],
  },
  {
    id: 'budget-splitter',
    name: 'Trip Budget Splitter',
    nameUrdu: 'سفری اخراجات تقسیم کار',
    tagline: 'Split group travel expenses fairly',
    taglineUrdu: 'گروپ سفری اخراجات منصفانہ تقسیم کریں',
    description: 'Add trip expenses, assign payers, and instantly see the minimum transactions to settle up — no more awkward maths.',
    icon: '🤝',
    path: '/tools/budget-splitter',
    color: '#8b5cf6',
    category: 'travel',
    tags: ['travel', 'budget', 'expenses', 'group', 'split'],
    related: ['currency-converter', 'packing-list'],
    features: ['Add any number of participants and expenses', 'Assign a different payer to each expense', 'Calculates minimum transactions to settle up', 'Works for groups of any size'],
  },
  // ── Health & Wellness ──
  {
    id: 'drug-checker',
    name: 'Drug Interaction Checker',
    nameUrdu: 'دوائی تعامل جانچ',
    tagline: 'Check medication interactions instantly',
    taglineUrdu: 'ادویات کے تعامل فوری چیک کریں',
    description: 'Enter your medications and supplements to see potential interactions — powered by the US National Library of Medicine (free, no data uploaded).',
    icon: '💊',
    path: '/tools/drug-checker',
    color: '#10b981',
    category: 'health',
    tags: ['health', 'medication', 'drugs', 'interactions', 'pharmacy'],
    related: ['symptom-tracker'],
    features: ['Check interactions between multiple medications', 'Search by generic or brand name', 'Powered by US National Library of Medicine API', 'Results include severity and clinical description'],
  },
  {
    id: 'symptom-tracker',
    name: 'Symptom Context Tracker',
    nameUrdu: 'علامات ٹریکر',
    tagline: 'Log symptoms with real-world context',
    taglineUrdu: 'حقیقی سیاق و سباق کے ساتھ علامات ریکارڈ کریں',
    description: 'Track how you feel alongside local weather, air pressure and temperature changes. Non-alarmist — understands your environment, not just your pain.',
    icon: '🩺',
    path: '/tools/symptom-tracker',
    color: '#f97316',
    category: 'health',
    tags: ['health', 'symptoms', 'wellness', 'weather', 'tracker'],
    related: ['drug-checker'],
    features: ['Log symptoms with severity, time and notes', 'Auto-records local weather: temperature and pressure', 'Correlates symptoms with weather changes', 'Data stays 100% on your device'],
  },
  {
    id: 'measurement-tracker',
    addedOn: '2026-04-15',
    name: 'Measurement Tracker',
    nameUrdu: 'پیمائش ٹریکر',
    tagline: 'Track any measurement over time',
    taglineUrdu: 'وقت کے ساتھ کوئی بھی پیمائش ٹریک کریں',
    description: 'Create custom trackers for body weight, room dimensions, temperature, blood pressure, or any metric you care about. Log entries over time and visualize trends.',
    icon: '📏',
    path: '/tools/measurement-tracker',
    color: '#8b5cf6',
    category: 'health',
    tags: ['measurement', 'tracker', 'health', 'body', 'weight', 'custom', 'log'],
    related: ['symptom-tracker', 'drug-checker'],
    features: ['Create custom trackers for any metric (weight, BP, dimensions)', 'Log entries over time with date and notes', 'Visualise trends with a line chart', 'All data stored locally'],
  },
  // ── Developer Tools ──────────────────────────────────────────────
  {
    id: 'data-transformer',
    name: 'Privacy-First Data Transformer',
    nameUrdu: 'ڈیٹا ٹرانسفارمر',
    tagline: 'Convert JSON, CSV & TSV 100% client-side',
    taglineUrdu: 'JSON، CSV اور TSV مکمل طور پر براؤزر میں تبدیل کریں',
    description: 'Transform data between JSON, CSV and TSV formats entirely in your browser — nothing leaves your machine. Includes a De-identifier toggle that auto-detects and masks emails, API keys and IP addresses.',
    icon: '🔄',
    path: '/tools/data-transformer',
    color: '#6366f1',
    category: 'developer',
    tags: ['json', 'csv', 'tsv', 'converter', 'privacy', 'developer'],
    related: ['config-converter', 'mock-data'],
    features: ['Convert between JSON, CSV and TSV formats', 'De-identifier toggle auto-masks emails, API keys and IPs', 'Live preview before downloading', 'No uploads -- handles large files locally'],
  },
  {
    id: 'markdown-scraper',
    name: 'LLM-Ready Markdown Scraper',
    nameUrdu: 'مارک ڈاؤن اسکریپر',
    tagline: 'Turn any URL into clean Markdown for AI',
    taglineUrdu: 'کسی بھی URL کو AI کے لیے مارک ڈاؤن بنائیں',
    description: 'Paste a URL or raw HTML and get clean, token-efficient Markdown optimised for LLM context windows. Generates a Table of Contents and strips code comments to keep output lean.',
    icon: '📄',
    path: '/tools/markdown-scraper',
    color: '#8b5cf6',
    category: 'developer',
    tags: ['markdown', 'scraper', 'llm', 'ai', 'html', 'developer'],
    related: ['data-transformer', 'log-analyzer'],
    features: ['Paste any URL or HTML to get clean Markdown', 'Auto-generates a Table of Contents', 'Token-efficient output for LLMs', 'Strips ads, nav and boilerplate'],
  },
  {
    id: 'log-analyzer',
    name: 'Smart Log Analyzer',
    nameUrdu: 'لاگ تجزیہ کار',
    tagline: 'Cluster errors and copy unique traces for AI',
    taglineUrdu: 'غلطیوں کو گروپ کریں اور AI کے لیے کاپی کریں',
    description: 'Paste raw server logs and instantly see errors grouped by pattern. The "Copy for AI" button extracts only unique stack traces, saving you from manually hunting through gigabytes of noise.',
    icon: '🪵',
    path: '/tools/log-analyzer',
    color: '#f59e0b',
    category: 'developer',
    tags: ['logs', 'errors', 'debugging', 'ai', 'devtools', 'developer'],
    related: ['markdown-scraper', 'data-transformer'],
    features: ['Paste server logs -- see errors grouped by pattern', 'Copy for AI extracts only unique stack traces', 'Filter by log level: ERROR, WARN, INFO', 'Handles gigabytes locally'],
  },
  {
    id: 'config-converter',
    name: 'Config Polyglot Converter',
    nameUrdu: 'کنفیگ کنورٹر',
    tagline: 'Convert .env ↔ JSON ↔ YAML ↔ TOML instantly',
    taglineUrdu: '.env ↔ JSON ↔ YAML ↔ TOML فوری تبدیل کریں',
    description: 'Drag-and-drop or paste any config file and convert between .env, JSON, YAML and TOML formats instantly in your browser — no uploads, no servers.',
    icon: '⚙️',
    path: '/tools/config-converter',
    color: '#0ea5e9',
    category: 'developer',
    tags: ['config', 'env', 'yaml', 'json', 'toml', 'converter', 'developer'],
    related: ['data-transformer', 'mock-data'],
    features: ['Convert between .env, JSON, YAML and TOML', 'Drag-and-drop or paste your config file', 'Validates syntax and shows errors inline', 'No uploads -- all conversion in browser'],
  },
  {
    id: 'mock-data',
    name: 'Mock Data Generator',
    nameUrdu: 'موک ڈیٹا جنریٹر',
    tagline: 'Generate bulk test data from a simple schema',
    taglineUrdu: 'آسان اسکیما سے بڑی مقدار میں ٹیسٹ ڈیٹا بنائیں',
    description: 'Define a quick schema (name, type, constraints) and generate thousands of unique rows in JSON or CSV. Edge Case mode purposely inserts nulls, zeros and special characters to stress-test your code.',
    icon: '🎲',
    path: '/tools/mock-data',
    color: '#ec4899',
    category: 'developer',
    tags: ['mock', 'data', 'testing', 'json', 'csv', 'generator', 'developer'],
    related: ['data-transformer', 'config-converter'],
    features: ['Define a schema with field names, types and constraints', 'Generate thousands of unique rows instantly', 'Edge Case mode inserts nulls and special characters', 'Download as JSON or CSV'],
  },
  {
    id: 'trace-correlator',
    name: 'Distributed Trace Correlator',
    nameUrdu: 'ٹریس کوریلیٹر',
    tagline: 'Correlate requests across microservices instantly',
    taglineUrdu: 'مائیکرو سروسز میں درخواستوں کو فوری جوڑیں',
    description: 'Drop multiple log files from different services. Instantly correlates requests by trace ID across all files with a swimlane timeline. 100% client-side — handles gigabytes without uploading anything.',
    icon: '🔗',
    path: '/tools/trace-correlator',
    color: '#8b5cf6',
    category: 'developer',
    tags: ['logs', 'tracing', 'microservices', 'debugging', 'enterprise', 'correlation', 'developer'],
    related: ['log-analyzer', 'data-leak-detector'],
    features: ['Drop multiple log files from different microservices', 'Correlates requests by trace ID across all files', 'Swimlane timeline shows exact sequence and timing', 'Handles gigabytes 100% locally'],
  },
  {
    id: 'schema-mapper',
    name: 'Schema Field Mapper',
    nameUrdu: 'اسکیما میپر',
    tagline: 'Visually map fields between schemas — generate transform code',
    taglineUrdu: 'اسکیما فیلڈز کو بصری طور پر میپ کریں',
    description: 'Paste source and destination JSON schemas, click to map fields, and instantly generate a JavaScript or Python transform function. Shows a complexity score and unmapped field warnings.',
    icon: '🗺️',
    path: '/tools/schema-mapper',
    color: '#06b6d4',
    category: 'developer',
    tags: ['schema', 'mapping', 'json', 'transform', 'code generation', 'etl', 'developer'],
    related: ['data-transformer', 'config-converter', 'trace-correlator'],
    features: ['Paste source and destination JSON schemas side-by-side', 'Click fields to create visual mappings', 'Generate JavaScript or Python transform code instantly', 'Complexity score and unmapped field warnings'],
  },
  // ── Education & Teaching ────────────────────────────────────────
  {
    id: 'student-groups',
    name: 'Student Group Randomizer',
    nameUrdu: 'طلبہ گروپ تقسیم کار',
    tagline: 'Balance skill levels across classroom groups',
    taglineUrdu: 'کلاس میں مہارت کی سطح کے مطابق متوازن گروپ بنائیں',
    description: 'Paste your class roster with skill levels and instantly generate balanced groups that mix ability levels — no manual sorting, no favoritism.',
    icon: '👥',
    path: '/tools/student-groups',
    color: '#ec4899',
    category: 'education',
    tags: ['education', 'teaching', 'classroom', 'groups', 'students'],
    related: [],
    features: ['Paste class roster with skill levels', 'Generates balanced groups mixing ability levels', 'Configurable group size', 'Multiple rounds without repeating pairs'],
  },
  // ── Legal & Research ───────────────────────────────────────────
  {
    id: 'timeline-builder',
    name: 'Contextual Timeline Builder',
    nameUrdu: 'ٹائم لائن ساز',
    tagline: 'Turn scattered dates into a visual timeline',
    taglineUrdu: 'بکھری تاریخوں کو بصری ٹائم لائن میں بدلیں',
    description: 'Paste events with dates in any format — emails, notes, bullet points. Auto-extracts dates and renders an interactive, exportable visual timeline for reports, cases, or projects.',
    icon: '📅',
    path: '/tools/timeline-builder',
    color: '#06b6d4',
    category: 'legal',
    tags: ['timeline', 'legal', 'research', 'dates', 'visualization'],
    related: [],
    features: ['Paste events in any format -- emails, notes, bullets', 'Auto-extracts dates from natural language', 'Renders an interactive visual timeline', 'Export as PDF or image for reports or cases'],
  },
  // ── Business & Field Work ──────────────────────────────────────
  {
    id: 'position-size-calc',
    name: 'Position Size Calculator',
    nameUrdu: 'پوزیشن سائز کیلکولیٹر',
    tagline: 'Risk exactly 1% — never over-leverage again',
    taglineUrdu: 'صحیح تجارتی پوزیشن حساب کریں، زیادہ خطرہ نہیں',
    description: 'Enter your account size, risk percentage, entry price and stop-loss. Instantly see how many shares to buy so you never risk more than you intend on any trade.',
    icon: '📊',
    path: '/tools/position-size-calc',
    color: '#10b981',
    category: 'business',
    tags: ['trading', 'stocks', 'risk', 'position', 'calculator', 'finance'],
    related: ['property-comp'],
    features: ['Enter account size, risk %, entry and stop-loss', 'Calculates shares to buy to avoid over-risking', 'Shows risk/reward ratio and potential profit', 'Supports any currency'],
  },
  {
    id: 'voice-invoice',
    name: 'Voice-to-Invoice',
    nameUrdu: 'وائس انوائس',
    tagline: 'Speak your job — get a formatted invoice',
    taglineUrdu: 'بولیں اور فارمیٹڈ انوائس حاصل کریں',
    description: 'Speak your work items while driving to the next job. The tool transcribes your words into clean, structured line-item invoice rows ready to download or copy into your billing software.',
    icon: '🎙️',
    path: '/tools/voice-invoice',
    color: '#f97316',
    category: 'business',
    tags: ['voice', 'invoice', 'hvac', 'field', 'billing', 'speech'],
    related: ['position-size-calc'],
    features: ['Speak your work items -- tool transcribes into invoice rows', 'Works while driving via microphone', 'Edit line items after transcription', 'Download invoice as PDF'],
  },
  {
    id: 'property-comp',
    name: 'Property Comp Adjuster',
    nameUrdu: 'پراپرٹی ویلیو ایڈجسٹر',
    tagline: 'Toggle features to calculate valuation delta',
    taglineUrdu: 'جائیداد کی قیمت کا موازنہ اور فرق حساب کریں',
    description: 'Compare a subject property against a comparable sale. Toggle differences in bedrooms, bathrooms, square footage and garage — see the adjusted valuation impact instantly.',
    icon: '🏠',
    path: '/tools/property-comp',
    color: '#8b5cf6',
    category: 'business',
    tags: ['real estate', 'appraisal', 'property', 'valuation', 'calculator'],
    related: ['position-size-calc'],
    features: ['Compare subject property against a comparable sale', 'Toggle feature differences: beds, baths, sqft, garage', 'Calculates adjusted valuation delta', 'Useful for appraisers and buyers'],
  },
  {
    id: 'refrigerant-calc',
    name: 'Refrigerant Leak Calculator',
    nameUrdu: 'ریفریجرینٹ لیک کیلکولیٹر',
    tagline: 'EPA leak rate compliance in seconds',
    taglineUrdu: 'لیک کی شرح فوری حساب کریں',
    description: 'Enter your system charge and refrigerant added to instantly calculate the annual leak rate percentage and compare it against EPA thresholds — know if a mandatory repair is required.',
    icon: '❄️',
    path: '/tools/refrigerant-calc',
    color: '#0ea5e9',
    category: 'business',
    tags: ['hvac', 'refrigerant', 'epa', 'compliance', 'calculator'],
    related: ['voice-invoice'],
    features: ['Enter system charge and refrigerant added', 'Calculates annual leak rate percentage', 'Compares against EPA thresholds', 'Indicates if mandatory repair is required'],
  },
  // ── Business ──────────────────────────────────────────────────
  {
    id: 'freelancer-risk',
    addedOn: '2026-03-20',
    name: 'Freelancer Risk Analyzer',
    nameUrdu: 'فری لانسر رسک تجزیہ کار',
    tagline: 'Score client risk before you start work',
    taglineUrdu: 'کام شروع کرنے سے پہلے کلائنٹ کا خطرہ جانچیں',
    description: 'Answer questions about your client source, contract terms, and payment structure — get a 0–100 risk score with specific, actionable advice. Save assessments for future reference.',
    icon: '🤝',
    path: '/tools/freelancer-risk',
    color: '#f59e0b',
    category: 'business',
    tags: ['freelancer', 'risk', 'contract', 'payment', 'upwork', 'fiverr', 'pakistan'],
    related: ['voice-invoice', 'position-size-calc'],
    features: ['Answer questions about client source, contract and payment', 'Get a 0-100 risk score with specific actionable advice', 'Save assessments for future reference', 'Covers Upwork, Fiverr, direct clients and more'],
  },
  {
    id: 'warranty-tracker',
    addedOn: '2026-04-10',
    name: 'Warranty Tracker',
    nameUrdu: 'وارنٹی ٹریکر',
    tagline: 'Never miss a warranty claim again',
    taglineUrdu: 'وارنٹی کی مدت ختم ہونے سے پہلے دعویٰ کریں',
    description: 'Track product warranties with expiry countdowns, status alerts and category filters. Get notified when warranties are about to expire so you can claim before it\'s too late.',
    icon: '🛡️',
    path: '/tools/warranty-tracker',
    color: '#3b82f6',
    category: 'business',
    tags: ['warranty', 'product', 'receipt', 'expiry', 'tracker', 'shopping', 'pakistan'],
    related: ['freelancer-risk'],
    features: ['Track product warranties with expiry countdowns', 'Status alerts: Active, Expiring Soon, Expired', 'Category filters: electronics, appliances, vehicles', 'Export warranty list as PDF'],
  },
  {
    id: 'driving-fines',
    addedOn: '2026-04-10',
    name: 'Driving Fine Tracker',
    nameUrdu: 'ٹریفک چالان ٹریکر',
    tagline: 'Track violations & monitor license suspension risk',
    taglineUrdu: 'خلاف ورزیاں اور لائسنس معطلی کا خطرہ مانیٹر کریں',
    description: 'Log traffic violations, track unpaid fines and monitor your license risk score against Pakistan Traffic Police suspension thresholds — all in one place.',
    icon: '🚦',
    path: '/tools/driving-fines',
    color: '#f97316',
    category: 'finance',
    tags: ['driving', 'traffic', 'challan', 'fine', 'license', 'pakistan', 'lahore', 'karachi'],
    related: ['expense-analyzer', 'tax-calculator'],
    features: ['Log traffic violations with date, location and fine amount', 'Track unpaid fines and payment deadlines', 'Monitor license suspension risk score', 'Based on Pakistan Traffic Police thresholds'],
  },
  // ── Finance (additional) ──────────────────────────────────────
  {
    id: 'expense-analyzer',
    addedOn: '2026-03-20',
    name: 'Expense Pattern Analyzer',
    nameUrdu: 'اخراجات تجزیہ کار',
    tagline: 'Understand where your money actually goes',
    taglineUrdu: 'جانیں آپ کا پیسہ کہاں جا رہا ہے',
    description: 'Upload your bank/Easypaisa/JazzCash CSV and get instant spending breakdowns, category charts, merchant insights and monthly trends — 100% private, runs in your browser.',
    icon: '💸',
    path: '/tools/expense-analyzer',
    color: '#10b981',
    category: 'finance',
    tags: ['expense', 'budget', 'finance', 'csv', 'bank', 'easypaisa', 'jazzcash', 'pakistan', 'spending'],
    related: ['tax-calculator', 'budget-splitter'],
    features: ['Upload bank, Easypaisa or JazzCash CSV', 'Instant spending breakdown by category', 'Merchant insights and monthly trends chart', '100% private -- no data leaves your browser'],
  },
  // ── Developer ─────────────────────────────────────────────────
  {
    id: 'data-leak-detector',
    name: 'Data Leak Detector',
    nameUrdu: 'ڈیٹا لیک ڈیٹیکٹر',
    tagline: 'Scan logs and configs for exposed secrets',
    taglineUrdu: 'لاگز اور کنفیگز میں بے نقاب راز تلاش کریں',
    description: 'Paste any text — logs, configs, API responses — and instantly detect exposed API keys, JWT tokens, AWS credentials, CNICs, IBANs, and more. Copy a safe redacted version in one click.',
    icon: '🕵️',
    path: '/tools/data-leak-detector',
    color: '#ef4444',
    category: 'developer',
    tags: ['security', 'secrets', 'api-keys', 'jwt', 'aws', 'leak', 'developer', 'devops'],
    related: ['doc-redaction', 'text-encryptor'],
  },
  // ── Security & Privacy ────────────────────────────────────────
  {
    id: 'doc-redaction',
    addedOn: '2026-03-20',
    name: 'Smart Document Redaction',
    nameUrdu: 'دستاویز ریڈیکشن',
    tagline: 'Redact sensitive info before sharing documents',
    taglineUrdu: 'دستاویزات شیئر کرنے سے پہلے حساس معلومات ہٹائیں',
    description: 'Automatically detects and redacts CNICs, IBANs, phone numbers, emails, NTNs, passports, credit cards and PKR amounts — 100% local, never leaves your browser.',
    icon: '🔏',
    path: '/tools/doc-redaction',
    color: '#6366f1',
    category: 'security',
    tags: ['privacy', 'redaction', 'cnic', 'iban', 'pii', 'document', 'security'],
    related: ['text-encryptor', 'doc-composer'],
    features: ['Auto-detects CNICs, IBANs, phone numbers, emails, NTNs', 'Redact any custom text patterns', 'One-click copy of safe redacted version', '100% local -- never leaves your browser'],
  },
  // ── PDF Tools ─────────────────────────────────────────────────
  {
    id: 'compress-pdf',
    addedOn: '2026-04-16',
    name: 'Compress PDF',
    nameUrdu: 'پی ڈی ایف چھوٹا کریں',
    tagline: 'Shrink any PDF — WhatsApp, Email, or Print ready',
    taglineUrdu: 'پی ڈی ایف سائز کم کریں — واٹس ایپ، ای میل یا پرنٹ کے لیے',
    description: 'Compress PDFs locally in your browser. Pick a preset: WhatsApp, Email, Print, or Archive. File never leaves your device.',
    icon: '🗜️',
    path: '/tools/compress-pdf',
    color: '#f97316',
    category: 'pdf',
    tags: ['pdf', 'compress', 'whatsapp', 'file size', 'optimize'],
    related: ['merge-pdf', 'split-pdf', 'pdf-convert'],
    features: ['Preset modes: WhatsApp, Email, Print, Archive', 'Shows before and after file size', 'Local browser processing -- no uploads', 'Handles multi-page PDFs quickly'],
  },
  {
    id: 'merge-pdf',
    addedOn: '2026-04-16',
    name: 'Merge PDF',
    nameUrdu: 'پی ڈی ایف جوڑیں',
    tagline: 'Combine multiple PDFs into one file',
    taglineUrdu: 'متعدد پی ڈی ایف فائلیں ایک میں ملائیں',
    description: 'Drag, reorder, and merge multiple PDFs into a single file. Optionally compress the result for WhatsApp sharing. 100% in-browser.',
    icon: '📎',
    path: '/tools/merge-pdf',
    color: '#8b5cf6',
    category: 'pdf',
    tags: ['pdf', 'merge', 'combine', 'join', 'files'],
    related: ['compress-pdf', 'split-pdf', 'pdf-convert'],
    features: ['Drag, reorder and merge multiple PDFs into one file', 'Optional compression after merge for WhatsApp sharing', 'Drag-and-drop page reordering', '100% in-browser'],
  },
  {
    id: 'split-pdf',
    addedOn: '2026-04-16',
    name: 'Split PDF',
    nameUrdu: 'پی ڈی ایف تقسیم کریں',
    tagline: 'Extract pages or split a PDF into parts',
    taglineUrdu: 'پی ڈی ایف سے صفحات نکالیں یا حصوں میں تقسیم کریں',
    description: 'Extract a single page, a custom range, or split every page into separate PDFs. Download as a ZIP. Fully local.',
    icon: '✂️',
    path: '/tools/split-pdf',
    color: '#ec4899',
    category: 'pdf',
    tags: ['pdf', 'split', 'extract', 'pages', 'separate'],
    related: ['merge-pdf', 'compress-pdf', 'pdf-convert'],
    features: ['Extract a single page, custom range or all pages', 'Download all extracted pages as a ZIP', 'Preview page thumbnails before splitting', 'Fully local processing'],
  },
  {
    id: 'pdf-convert',
    addedOn: '2026-04-16',
    name: 'PDF Convert',
    nameUrdu: 'پی ڈی ایف کنورٹ کریں',
    tagline: 'Convert PDF to JPG or images to PDF',
    taglineUrdu: 'پی ڈی ایف کو تصویر میں یا تصویر کو پی ڈی ایف میں بدلیں',
    description: 'Convert PDF pages to JPG images (download as ZIP) or combine multiple images into a single PDF. All processing in your browser.',
    icon: '🔄',
    path: '/tools/pdf-convert',
    color: '#06b6d4',
    category: 'pdf',
    tags: ['pdf', 'convert', 'jpg', 'image', 'png', 'photos'],
    related: ['compress-pdf', 'merge-pdf', 'split-pdf'],
    features: ['Convert PDF pages to JPG images (ZIP download)', 'Combine multiple images into a single PDF', 'Adjustable image quality', 'All processing in your browser'],
  },
  {
    id: 'doc-converter',
    addedOn: '2026-04-16',
    name: 'Doc Converter',
    tagline: 'Convert DOCX to PDF or PDF to Word',
    description: 'Convert DOCX files to PDF or extract PDF text into a .docx file. 100% client-side.',
    icon: '📝',
    path: '/tools/doc-converter',
    color: '#3b82f6',
    category: 'pdf',
    tags: ['pdf', 'docx', 'word', 'convert', 'document'],
    related: ['compress-pdf', 'pdf-convert', 'doc-composer'],
    features: ['Convert DOCX files to PDF', 'Extract PDF text into a .docx file', 'Drag-and-drop file input', '100% client-side processing'],
  },
  {
    id: 'text-extractor',
    addedOn: '2026-04-16',
    name: 'Text Extractor (OCR)',
    tagline: 'Extract text from images or scanned PDFs',
    description: 'Upload any image or PDF and extract all text via Tesseract.js OCR. Supports English, Urdu, Arabic. 100% local.',
    icon: '🔬',
    path: '/tools/text-extractor',
    color: '#10b981',
    category: 'pdf',
    tags: ['ocr', 'image', 'text', 'extract', 'scan', 'urdu', 'arabic'],
    related: ['pdf-search', 'doc-converter', 'doc-redaction'],
    features: ['Extract text from images via OCR (English, Urdu, Arabic)', 'Extract text from PDF files', 'Scanned PDF OCR with progress tracking', 'Tesseract.js-powered -- no upload needed'],
  },
  {
    id: 'pdf-search',
    addedOn: '2026-04-16',
    name: 'PDF Search',
    tagline: 'Search for any text inside a PDF file',
    description: 'Upload a PDF and instantly search for any keyword. Shows matching pages with context snippets.',
    icon: '🔎',
    path: '/tools/pdf-search',
    color: '#f59e0b',
    category: 'pdf',
    tags: ['pdf', 'search', 'find', 'keyword', 'text'],
    related: ['text-extractor', 'doc-redaction', 'compress-pdf'],
    features: ['Upload a PDF and search for any keyword', 'Shows matching context snippets with highlights', 'Navigate directly to pages with matches', 'Local processing -- your PDF never leaves the browser'],
  },
]

export function getToolById(id) {
  return TOOLS.find((t) => t.id === id) || null
}

/** Get related tool objects for a given tool id. */
export function getRelatedTools(id) {
  const tool = getToolById(id)
  if (!tool) return []
  return (tool.related || []).map(getToolById).filter(Boolean)
}




